// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CallPhone.proto

package com.qzy.tt.data;

public final class CallPhoneProtos {
  private CallPhoneProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CallPhoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:phonedata.CallPhone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string ip = 1;</code>
     */
    String getIp();
    /**
     * <code>optional string ip = 1;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>optional string phoneNumber = 2;</code>
     */
    String getPhoneNumber();
    /**
     * <code>optional string phoneNumber = 2;</code>
     */
    com.google.protobuf.ByteString
        getPhoneNumberBytes();

    /**
     * <code>optional .phonedata.CallPhone.PhoneCommand phonecommand = 3;</code>
     */
    int getPhonecommandValue();
    /**
     * <code>optional .phonedata.CallPhone.PhoneCommand phonecommand = 3;</code>
     */
    CallPhone.PhoneCommand getPhonecommand();
  }
  /**
   * Protobuf type {@code phonedata.CallPhone}
   */
  public  static final class CallPhone extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:phonedata.CallPhone)
      CallPhoneOrBuilder {
    // Use CallPhone.newBuilder() to construct.
    private CallPhone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CallPhone() {
      ip_ = "";
      phoneNumber_ = "";
      phonecommand_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CallPhone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              phoneNumber_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              phonecommand_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CallPhoneProtos.internal_static_phonedata_CallPhone_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CallPhoneProtos.internal_static_phonedata_CallPhone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CallPhone.class, Builder.class);
    }

    /**
     * Protobuf enum {@code phonedata.CallPhone.PhoneCommand}
     */
    public enum PhoneCommand
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NONE = 0;</code>
       */
      NONE(0),
      /**
       * <code>CALL = 1;</code>
       */
      CALL(1),
      /**
       * <code>HUANGUP = 2;</code>
       */
      HUANGUP(2),
      /**
       * <code>ACCEPTCALL = 3;</code>
       */
      ACCEPTCALL(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <code>CALL = 1;</code>
       */
      public static final int CALL_VALUE = 1;
      /**
       * <code>HUANGUP = 2;</code>
       */
      public static final int HUANGUP_VALUE = 2;
      /**
       * <code>ACCEPTCALL = 3;</code>
       */
      public static final int ACCEPTCALL_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static PhoneCommand valueOf(int value) {
        return forNumber(value);
      }

      public static PhoneCommand forNumber(int value) {
        switch (value) {
          case 0: return NONE;
          case 1: return CALL;
          case 2: return HUANGUP;
          case 3: return ACCEPTCALL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneCommand>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhoneCommand> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneCommand>() {
              public PhoneCommand findValueByNumber(int number) {
                return PhoneCommand.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return CallPhone.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneCommand[] VALUES = values();

      public static PhoneCommand valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PhoneCommand(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:phonedata.CallPhone.PhoneCommand)
    }

    public static final int IP_FIELD_NUMBER = 1;
    private volatile Object ip_;
    /**
     * <code>optional string ip = 1;</code>
     */
    public String getIp() {
      Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ip = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 2;
    private volatile Object phoneNumber_;
    /**
     * <code>optional string phoneNumber = 2;</code>
     */
    public String getPhoneNumber() {
      Object ref = phoneNumber_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        phoneNumber_ = s;
        return s;
      }
    }
    /**
     * <code>optional string phoneNumber = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      Object ref = phoneNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONECOMMAND_FIELD_NUMBER = 3;
    private int phonecommand_;
    /**
     * <code>optional .phonedata.CallPhone.PhoneCommand phonecommand = 3;</code>
     */
    public int getPhonecommandValue() {
      return phonecommand_;
    }
    /**
     * <code>optional .phonedata.CallPhone.PhoneCommand phonecommand = 3;</code>
     */
    public PhoneCommand getPhonecommand() {
      PhoneCommand result = PhoneCommand.valueOf(phonecommand_);
      return result == null ? PhoneCommand.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ip_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, phoneNumber_);
      }
      if (phonecommand_ != PhoneCommand.NONE.getNumber()) {
        output.writeEnum(3, phonecommand_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ip_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, phoneNumber_);
      }
      if (phonecommand_ != PhoneCommand.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, phonecommand_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CallPhone)) {
        return super.equals(obj);
      }
      CallPhone other = (CallPhone) obj;

      boolean result = true;
      result = result && getIp()
          .equals(other.getIp());
      result = result && getPhoneNumber()
          .equals(other.getPhoneNumber());
      result = result && phonecommand_ == other.phonecommand_;
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumber().hashCode();
      hash = (37 * hash) + PHONECOMMAND_FIELD_NUMBER;
      hash = (53 * hash) + phonecommand_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CallPhone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallPhone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallPhone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallPhone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallPhone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CallPhone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CallPhone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CallPhone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CallPhone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CallPhone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CallPhone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code phonedata.CallPhone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:phonedata.CallPhone)
        CallPhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CallPhoneProtos.internal_static_phonedata_CallPhone_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CallPhoneProtos.internal_static_phonedata_CallPhone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CallPhone.class, Builder.class);
      }

      // Construct using com.qzy.tt.data.CallPhoneProtos.CallPhone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ip_ = "";

        phoneNumber_ = "";

        phonecommand_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CallPhoneProtos.internal_static_phonedata_CallPhone_descriptor;
      }

      public CallPhone getDefaultInstanceForType() {
        return CallPhone.getDefaultInstance();
      }

      public CallPhone build() {
        CallPhone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CallPhone buildPartial() {
        CallPhone result = new CallPhone(this);
        result.ip_ = ip_;
        result.phoneNumber_ = phoneNumber_;
        result.phonecommand_ = phonecommand_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CallPhone) {
          return mergeFrom((CallPhone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CallPhone other) {
        if (other == CallPhone.getDefaultInstance()) return this;
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (!other.getPhoneNumber().isEmpty()) {
          phoneNumber_ = other.phoneNumber_;
          onChanged();
        }
        if (other.phonecommand_ != 0) {
          setPhonecommandValue(other.getPhonecommandValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CallPhone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CallPhone) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object ip_ = "";
      /**
       * <code>optional string ip = 1;</code>
       */
      public String getIp() {
        Object ref = ip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder setIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private Object phoneNumber_ = "";
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      public String getPhoneNumber() {
        Object ref = phoneNumber_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          phoneNumber_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumberBytes() {
        Object ref = phoneNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          phoneNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      public Builder setPhoneNumber(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      public Builder clearPhoneNumber() {
        
        phoneNumber_ = getDefaultInstance().getPhoneNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      public Builder setPhoneNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneNumber_ = value;
        onChanged();
        return this;
      }

      private int phonecommand_ = 0;
      /**
       * <code>optional .phonedata.CallPhone.PhoneCommand phonecommand = 3;</code>
       */
      public int getPhonecommandValue() {
        return phonecommand_;
      }
      /**
       * <code>optional .phonedata.CallPhone.PhoneCommand phonecommand = 3;</code>
       */
      public Builder setPhonecommandValue(int value) {
        phonecommand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .phonedata.CallPhone.PhoneCommand phonecommand = 3;</code>
       */
      public PhoneCommand getPhonecommand() {
        PhoneCommand result = PhoneCommand.valueOf(phonecommand_);
        return result == null ? PhoneCommand.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .phonedata.CallPhone.PhoneCommand phonecommand = 3;</code>
       */
      public Builder setPhonecommand(PhoneCommand value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        phonecommand_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .phonedata.CallPhone.PhoneCommand phonecommand = 3;</code>
       */
      public Builder clearPhonecommand() {
        
        phonecommand_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:phonedata.CallPhone)
    }

    // @@protoc_insertion_point(class_scope:phonedata.CallPhone)
    private static final CallPhone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CallPhone();
    }

    public static CallPhone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CallPhone>
        PARSER = new com.google.protobuf.AbstractParser<CallPhone>() {
      public CallPhone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CallPhone(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CallPhone> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CallPhone> getParserForType() {
      return PARSER;
    }

    public CallPhone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_phonedata_CallPhone_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_phonedata_CallPhone_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017CallPhone.proto\022\tphonedata\"\246\001\n\tCallPho" +
      "ne\022\n\n\002ip\030\001 \001(\t\022\023\n\013phoneNumber\030\002 \001(\t\0227\n\014p" +
      "honecommand\030\003 \001(\0162!.phonedata.CallPhone." +
      "PhoneCommand\"?\n\014PhoneCommand\022\010\n\004NONE\020\000\022\010" +
      "\n\004CALL\020\001\022\013\n\007HUANGUP\020\002\022\016\n\nACCEPTCALL\020\003B\"\n" +
      "\017com.qzy.tt.dataB\017CallPhoneProtosb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_phonedata_CallPhone_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_phonedata_CallPhone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_phonedata_CallPhone_descriptor,
        new String[] { "Ip", "PhoneNumber", "Phonecommand", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
