// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TimerSend.proto

package com.qzy.tt.data;

public final class TimerSendProtos {
  private TimerSendProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TimerSendOrBuilder extends
      // @@protoc_insertion_point(interface_extends:phonedata.TimerSend)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *当前通话状态
     * </pre>
     *
     * <code>optional .phonedata.CallPhoneState callPhoneState = 1;</code>
     */
    boolean hasCallPhoneState();
    /**
     * <pre>
     *当前通话状态
     * </pre>
     *
     * <code>optional .phonedata.CallPhoneState callPhoneState = 1;</code>
     */
    CallPhoneStateProtos.CallPhoneState getCallPhoneState();
    /**
     * <pre>
     *当前通话状态
     * </pre>
     *
     * <code>optional .phonedata.CallPhoneState callPhoneState = 1;</code>
     */
    CallPhoneStateProtos.CallPhoneStateOrBuilder getCallPhoneStateOrBuilder();

    /**
     * <pre>
     *手机信号强度
     * </pre>
     *
     * <code>optional .phonedata.PhoneSignalStrength sigalStrength = 2;</code>
     */
    boolean hasSigalStrength();
    /**
     * <pre>
     *手机信号强度
     * </pre>
     *
     * <code>optional .phonedata.PhoneSignalStrength sigalStrength = 2;</code>
     */
    TtPhoneSignalProtos.PhoneSignalStrength getSigalStrength();
    /**
     * <pre>
     *手机信号强度
     * </pre>
     *
     * <code>optional .phonedata.PhoneSignalStrength sigalStrength = 2;</code>
     */
    TtPhoneSignalProtos.PhoneSignalStrengthOrBuilder getSigalStrengthOrBuilder();

    /**
     * <pre>
     *电量
     * </pre>
     *
     * <code>optional .phonedata.TtPhoneBattery batterValue = 3;</code>
     */
    boolean hasBatterValue();
    /**
     * <pre>
     *电量
     * </pre>
     *
     * <code>optional .phonedata.TtPhoneBattery batterValue = 3;</code>
     */
    TtPhoneBatteryProtos.TtPhoneBattery getBatterValue();
    /**
     * <pre>
     *电量
     * </pre>
     *
     * <code>optional .phonedata.TtPhoneBattery batterValue = 3;</code>
     */
    TtPhoneBatteryProtos.TtPhoneBatteryOrBuilder getBatterValueOrBuilder();

    /**
     * <pre>
     *sim 卡
     * </pre>
     *
     * <code>optional .phonedata.TtPhoneSimCard ttPhoneSimcard = 4;</code>
     */
    boolean hasTtPhoneSimcard();
    /**
     * <pre>
     *sim 卡
     * </pre>
     *
     * <code>optional .phonedata.TtPhoneSimCard ttPhoneSimcard = 4;</code>
     */
    TtPhoneSimCards.TtPhoneSimCard getTtPhoneSimcard();
    /**
     * <pre>
     *sim 卡
     * </pre>
     *
     * <code>optional .phonedata.TtPhoneSimCard ttPhoneSimcard = 4;</code>
     */
    TtPhoneSimCards.TtPhoneSimCardOrBuilder getTtPhoneSimcardOrBuilder();

    /**
     * <pre>
     *gps
     * </pre>
     *
     * <code>optional .phonedata.TtPhonePosition ttPhoneGpsPosition = 5;</code>
     */
    boolean hasTtPhoneGpsPosition();
    /**
     * <pre>
     *gps
     * </pre>
     *
     * <code>optional .phonedata.TtPhonePosition ttPhoneGpsPosition = 5;</code>
     */
    TtPhonePositionProtos.TtPhonePosition getTtPhoneGpsPosition();
    /**
     * <pre>
     *gps
     * </pre>
     *
     * <code>optional .phonedata.TtPhonePosition ttPhoneGpsPosition = 5;</code>
     */
    TtPhonePositionProtos.TtPhonePositionOrBuilder getTtPhoneGpsPositionOrBuilder();
  }
  /**
   * Protobuf type {@code phonedata.TimerSend}
   */
  public  static final class TimerSend extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:phonedata.TimerSend)
      TimerSendOrBuilder {
    // Use TimerSend.newBuilder() to construct.
    private TimerSend(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TimerSend() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TimerSend(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              CallPhoneStateProtos.CallPhoneState.Builder subBuilder = null;
              if (callPhoneState_ != null) {
                subBuilder = callPhoneState_.toBuilder();
              }
              callPhoneState_ = input.readMessage(CallPhoneStateProtos.CallPhoneState.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(callPhoneState_);
                callPhoneState_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              TtPhoneSignalProtos.PhoneSignalStrength.Builder subBuilder = null;
              if (sigalStrength_ != null) {
                subBuilder = sigalStrength_.toBuilder();
              }
              sigalStrength_ = input.readMessage(TtPhoneSignalProtos.PhoneSignalStrength.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sigalStrength_);
                sigalStrength_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              TtPhoneBatteryProtos.TtPhoneBattery.Builder subBuilder = null;
              if (batterValue_ != null) {
                subBuilder = batterValue_.toBuilder();
              }
              batterValue_ = input.readMessage(TtPhoneBatteryProtos.TtPhoneBattery.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(batterValue_);
                batterValue_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              TtPhoneSimCards.TtPhoneSimCard.Builder subBuilder = null;
              if (ttPhoneSimcard_ != null) {
                subBuilder = ttPhoneSimcard_.toBuilder();
              }
              ttPhoneSimcard_ = input.readMessage(TtPhoneSimCards.TtPhoneSimCard.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ttPhoneSimcard_);
                ttPhoneSimcard_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              TtPhonePositionProtos.TtPhonePosition.Builder subBuilder = null;
              if (ttPhoneGpsPosition_ != null) {
                subBuilder = ttPhoneGpsPosition_.toBuilder();
              }
              ttPhoneGpsPosition_ = input.readMessage(TtPhonePositionProtos.TtPhonePosition.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ttPhoneGpsPosition_);
                ttPhoneGpsPosition_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TimerSendProtos.internal_static_phonedata_TimerSend_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TimerSendProtos.internal_static_phonedata_TimerSend_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TimerSend.class, Builder.class);
    }

    public static final int CALLPHONESTATE_FIELD_NUMBER = 1;
    private CallPhoneStateProtos.CallPhoneState callPhoneState_;
    /**
     * <pre>
     *当前通话状态
     * </pre>
     *
     * <code>optional .phonedata.CallPhoneState callPhoneState = 1;</code>
     */
    public boolean hasCallPhoneState() {
      return callPhoneState_ != null;
    }
    /**
     * <pre>
     *当前通话状态
     * </pre>
     *
     * <code>optional .phonedata.CallPhoneState callPhoneState = 1;</code>
     */
    public CallPhoneStateProtos.CallPhoneState getCallPhoneState() {
      return callPhoneState_ == null ? CallPhoneStateProtos.CallPhoneState.getDefaultInstance() : callPhoneState_;
    }
    /**
     * <pre>
     *当前通话状态
     * </pre>
     *
     * <code>optional .phonedata.CallPhoneState callPhoneState = 1;</code>
     */
    public CallPhoneStateProtos.CallPhoneStateOrBuilder getCallPhoneStateOrBuilder() {
      return getCallPhoneState();
    }

    public static final int SIGALSTRENGTH_FIELD_NUMBER = 2;
    private TtPhoneSignalProtos.PhoneSignalStrength sigalStrength_;
    /**
     * <pre>
     *手机信号强度
     * </pre>
     *
     * <code>optional .phonedata.PhoneSignalStrength sigalStrength = 2;</code>
     */
    public boolean hasSigalStrength() {
      return sigalStrength_ != null;
    }
    /**
     * <pre>
     *手机信号强度
     * </pre>
     *
     * <code>optional .phonedata.PhoneSignalStrength sigalStrength = 2;</code>
     */
    public TtPhoneSignalProtos.PhoneSignalStrength getSigalStrength() {
      return sigalStrength_ == null ? TtPhoneSignalProtos.PhoneSignalStrength.getDefaultInstance() : sigalStrength_;
    }
    /**
     * <pre>
     *手机信号强度
     * </pre>
     *
     * <code>optional .phonedata.PhoneSignalStrength sigalStrength = 2;</code>
     */
    public TtPhoneSignalProtos.PhoneSignalStrengthOrBuilder getSigalStrengthOrBuilder() {
      return getSigalStrength();
    }

    public static final int BATTERVALUE_FIELD_NUMBER = 3;
    private TtPhoneBatteryProtos.TtPhoneBattery batterValue_;
    /**
     * <pre>
     *电量
     * </pre>
     *
     * <code>optional .phonedata.TtPhoneBattery batterValue = 3;</code>
     */
    public boolean hasBatterValue() {
      return batterValue_ != null;
    }
    /**
     * <pre>
     *电量
     * </pre>
     *
     * <code>optional .phonedata.TtPhoneBattery batterValue = 3;</code>
     */
    public TtPhoneBatteryProtos.TtPhoneBattery getBatterValue() {
      return batterValue_ == null ? TtPhoneBatteryProtos.TtPhoneBattery.getDefaultInstance() : batterValue_;
    }
    /**
     * <pre>
     *电量
     * </pre>
     *
     * <code>optional .phonedata.TtPhoneBattery batterValue = 3;</code>
     */
    public TtPhoneBatteryProtos.TtPhoneBatteryOrBuilder getBatterValueOrBuilder() {
      return getBatterValue();
    }

    public static final int TTPHONESIMCARD_FIELD_NUMBER = 4;
    private TtPhoneSimCards.TtPhoneSimCard ttPhoneSimcard_;
    /**
     * <pre>
     *sim 卡
     * </pre>
     *
     * <code>optional .phonedata.TtPhoneSimCard ttPhoneSimcard = 4;</code>
     */
    public boolean hasTtPhoneSimcard() {
      return ttPhoneSimcard_ != null;
    }
    /**
     * <pre>
     *sim 卡
     * </pre>
     *
     * <code>optional .phonedata.TtPhoneSimCard ttPhoneSimcard = 4;</code>
     */
    public TtPhoneSimCards.TtPhoneSimCard getTtPhoneSimcard() {
      return ttPhoneSimcard_ == null ? TtPhoneSimCards.TtPhoneSimCard.getDefaultInstance() : ttPhoneSimcard_;
    }
    /**
     * <pre>
     *sim 卡
     * </pre>
     *
     * <code>optional .phonedata.TtPhoneSimCard ttPhoneSimcard = 4;</code>
     */
    public TtPhoneSimCards.TtPhoneSimCardOrBuilder getTtPhoneSimcardOrBuilder() {
      return getTtPhoneSimcard();
    }

    public static final int TTPHONEGPSPOSITION_FIELD_NUMBER = 5;
    private TtPhonePositionProtos.TtPhonePosition ttPhoneGpsPosition_;
    /**
     * <pre>
     *gps
     * </pre>
     *
     * <code>optional .phonedata.TtPhonePosition ttPhoneGpsPosition = 5;</code>
     */
    public boolean hasTtPhoneGpsPosition() {
      return ttPhoneGpsPosition_ != null;
    }
    /**
     * <pre>
     *gps
     * </pre>
     *
     * <code>optional .phonedata.TtPhonePosition ttPhoneGpsPosition = 5;</code>
     */
    public TtPhonePositionProtos.TtPhonePosition getTtPhoneGpsPosition() {
      return ttPhoneGpsPosition_ == null ? TtPhonePositionProtos.TtPhonePosition.getDefaultInstance() : ttPhoneGpsPosition_;
    }
    /**
     * <pre>
     *gps
     * </pre>
     *
     * <code>optional .phonedata.TtPhonePosition ttPhoneGpsPosition = 5;</code>
     */
    public TtPhonePositionProtos.TtPhonePositionOrBuilder getTtPhoneGpsPositionOrBuilder() {
      return getTtPhoneGpsPosition();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (callPhoneState_ != null) {
        output.writeMessage(1, getCallPhoneState());
      }
      if (sigalStrength_ != null) {
        output.writeMessage(2, getSigalStrength());
      }
      if (batterValue_ != null) {
        output.writeMessage(3, getBatterValue());
      }
      if (ttPhoneSimcard_ != null) {
        output.writeMessage(4, getTtPhoneSimcard());
      }
      if (ttPhoneGpsPosition_ != null) {
        output.writeMessage(5, getTtPhoneGpsPosition());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (callPhoneState_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCallPhoneState());
      }
      if (sigalStrength_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSigalStrength());
      }
      if (batterValue_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getBatterValue());
      }
      if (ttPhoneSimcard_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getTtPhoneSimcard());
      }
      if (ttPhoneGpsPosition_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getTtPhoneGpsPosition());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TimerSend)) {
        return super.equals(obj);
      }
      TimerSend other = (TimerSend) obj;

      boolean result = true;
      result = result && (hasCallPhoneState() == other.hasCallPhoneState());
      if (hasCallPhoneState()) {
        result = result && getCallPhoneState()
            .equals(other.getCallPhoneState());
      }
      result = result && (hasSigalStrength() == other.hasSigalStrength());
      if (hasSigalStrength()) {
        result = result && getSigalStrength()
            .equals(other.getSigalStrength());
      }
      result = result && (hasBatterValue() == other.hasBatterValue());
      if (hasBatterValue()) {
        result = result && getBatterValue()
            .equals(other.getBatterValue());
      }
      result = result && (hasTtPhoneSimcard() == other.hasTtPhoneSimcard());
      if (hasTtPhoneSimcard()) {
        result = result && getTtPhoneSimcard()
            .equals(other.getTtPhoneSimcard());
      }
      result = result && (hasTtPhoneGpsPosition() == other.hasTtPhoneGpsPosition());
      if (hasTtPhoneGpsPosition()) {
        result = result && getTtPhoneGpsPosition()
            .equals(other.getTtPhoneGpsPosition());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasCallPhoneState()) {
        hash = (37 * hash) + CALLPHONESTATE_FIELD_NUMBER;
        hash = (53 * hash) + getCallPhoneState().hashCode();
      }
      if (hasSigalStrength()) {
        hash = (37 * hash) + SIGALSTRENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getSigalStrength().hashCode();
      }
      if (hasBatterValue()) {
        hash = (37 * hash) + BATTERVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getBatterValue().hashCode();
      }
      if (hasTtPhoneSimcard()) {
        hash = (37 * hash) + TTPHONESIMCARD_FIELD_NUMBER;
        hash = (53 * hash) + getTtPhoneSimcard().hashCode();
      }
      if (hasTtPhoneGpsPosition()) {
        hash = (37 * hash) + TTPHONEGPSPOSITION_FIELD_NUMBER;
        hash = (53 * hash) + getTtPhoneGpsPosition().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TimerSend parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TimerSend parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TimerSend parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TimerSend parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TimerSend parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TimerSend parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TimerSend parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TimerSend parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TimerSend parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TimerSend parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TimerSend prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code phonedata.TimerSend}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:phonedata.TimerSend)
        TimerSendOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TimerSendProtos.internal_static_phonedata_TimerSend_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TimerSendProtos.internal_static_phonedata_TimerSend_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TimerSend.class, Builder.class);
      }

      // Construct using com.qzy.tt.data.TimerSendProtos.TimerSend.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (callPhoneStateBuilder_ == null) {
          callPhoneState_ = null;
        } else {
          callPhoneState_ = null;
          callPhoneStateBuilder_ = null;
        }
        if (sigalStrengthBuilder_ == null) {
          sigalStrength_ = null;
        } else {
          sigalStrength_ = null;
          sigalStrengthBuilder_ = null;
        }
        if (batterValueBuilder_ == null) {
          batterValue_ = null;
        } else {
          batterValue_ = null;
          batterValueBuilder_ = null;
        }
        if (ttPhoneSimcardBuilder_ == null) {
          ttPhoneSimcard_ = null;
        } else {
          ttPhoneSimcard_ = null;
          ttPhoneSimcardBuilder_ = null;
        }
        if (ttPhoneGpsPositionBuilder_ == null) {
          ttPhoneGpsPosition_ = null;
        } else {
          ttPhoneGpsPosition_ = null;
          ttPhoneGpsPositionBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TimerSendProtos.internal_static_phonedata_TimerSend_descriptor;
      }

      public TimerSend getDefaultInstanceForType() {
        return TimerSend.getDefaultInstance();
      }

      public TimerSend build() {
        TimerSend result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TimerSend buildPartial() {
        TimerSend result = new TimerSend(this);
        if (callPhoneStateBuilder_ == null) {
          result.callPhoneState_ = callPhoneState_;
        } else {
          result.callPhoneState_ = callPhoneStateBuilder_.build();
        }
        if (sigalStrengthBuilder_ == null) {
          result.sigalStrength_ = sigalStrength_;
        } else {
          result.sigalStrength_ = sigalStrengthBuilder_.build();
        }
        if (batterValueBuilder_ == null) {
          result.batterValue_ = batterValue_;
        } else {
          result.batterValue_ = batterValueBuilder_.build();
        }
        if (ttPhoneSimcardBuilder_ == null) {
          result.ttPhoneSimcard_ = ttPhoneSimcard_;
        } else {
          result.ttPhoneSimcard_ = ttPhoneSimcardBuilder_.build();
        }
        if (ttPhoneGpsPositionBuilder_ == null) {
          result.ttPhoneGpsPosition_ = ttPhoneGpsPosition_;
        } else {
          result.ttPhoneGpsPosition_ = ttPhoneGpsPositionBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TimerSend) {
          return mergeFrom((TimerSend)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TimerSend other) {
        if (other == TimerSend.getDefaultInstance()) return this;
        if (other.hasCallPhoneState()) {
          mergeCallPhoneState(other.getCallPhoneState());
        }
        if (other.hasSigalStrength()) {
          mergeSigalStrength(other.getSigalStrength());
        }
        if (other.hasBatterValue()) {
          mergeBatterValue(other.getBatterValue());
        }
        if (other.hasTtPhoneSimcard()) {
          mergeTtPhoneSimcard(other.getTtPhoneSimcard());
        }
        if (other.hasTtPhoneGpsPosition()) {
          mergeTtPhoneGpsPosition(other.getTtPhoneGpsPosition());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TimerSend parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TimerSend) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private CallPhoneStateProtos.CallPhoneState callPhoneState_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          CallPhoneStateProtos.CallPhoneState, CallPhoneStateProtos.CallPhoneState.Builder, CallPhoneStateProtos.CallPhoneStateOrBuilder> callPhoneStateBuilder_;
      /**
       * <pre>
       *当前通话状态
       * </pre>
       *
       * <code>optional .phonedata.CallPhoneState callPhoneState = 1;</code>
       */
      public boolean hasCallPhoneState() {
        return callPhoneStateBuilder_ != null || callPhoneState_ != null;
      }
      /**
       * <pre>
       *当前通话状态
       * </pre>
       *
       * <code>optional .phonedata.CallPhoneState callPhoneState = 1;</code>
       */
      public CallPhoneStateProtos.CallPhoneState getCallPhoneState() {
        if (callPhoneStateBuilder_ == null) {
          return callPhoneState_ == null ? CallPhoneStateProtos.CallPhoneState.getDefaultInstance() : callPhoneState_;
        } else {
          return callPhoneStateBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *当前通话状态
       * </pre>
       *
       * <code>optional .phonedata.CallPhoneState callPhoneState = 1;</code>
       */
      public Builder setCallPhoneState(CallPhoneStateProtos.CallPhoneState value) {
        if (callPhoneStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          callPhoneState_ = value;
          onChanged();
        } else {
          callPhoneStateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *当前通话状态
       * </pre>
       *
       * <code>optional .phonedata.CallPhoneState callPhoneState = 1;</code>
       */
      public Builder setCallPhoneState(
          CallPhoneStateProtos.CallPhoneState.Builder builderForValue) {
        if (callPhoneStateBuilder_ == null) {
          callPhoneState_ = builderForValue.build();
          onChanged();
        } else {
          callPhoneStateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *当前通话状态
       * </pre>
       *
       * <code>optional .phonedata.CallPhoneState callPhoneState = 1;</code>
       */
      public Builder mergeCallPhoneState(CallPhoneStateProtos.CallPhoneState value) {
        if (callPhoneStateBuilder_ == null) {
          if (callPhoneState_ != null) {
            callPhoneState_ =
              CallPhoneStateProtos.CallPhoneState.newBuilder(callPhoneState_).mergeFrom(value).buildPartial();
          } else {
            callPhoneState_ = value;
          }
          onChanged();
        } else {
          callPhoneStateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *当前通话状态
       * </pre>
       *
       * <code>optional .phonedata.CallPhoneState callPhoneState = 1;</code>
       */
      public Builder clearCallPhoneState() {
        if (callPhoneStateBuilder_ == null) {
          callPhoneState_ = null;
          onChanged();
        } else {
          callPhoneState_ = null;
          callPhoneStateBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *当前通话状态
       * </pre>
       *
       * <code>optional .phonedata.CallPhoneState callPhoneState = 1;</code>
       */
      public CallPhoneStateProtos.CallPhoneState.Builder getCallPhoneStateBuilder() {
        
        onChanged();
        return getCallPhoneStateFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *当前通话状态
       * </pre>
       *
       * <code>optional .phonedata.CallPhoneState callPhoneState = 1;</code>
       */
      public CallPhoneStateProtos.CallPhoneStateOrBuilder getCallPhoneStateOrBuilder() {
        if (callPhoneStateBuilder_ != null) {
          return callPhoneStateBuilder_.getMessageOrBuilder();
        } else {
          return callPhoneState_ == null ?
              CallPhoneStateProtos.CallPhoneState.getDefaultInstance() : callPhoneState_;
        }
      }
      /**
       * <pre>
       *当前通话状态
       * </pre>
       *
       * <code>optional .phonedata.CallPhoneState callPhoneState = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CallPhoneStateProtos.CallPhoneState, CallPhoneStateProtos.CallPhoneState.Builder, CallPhoneStateProtos.CallPhoneStateOrBuilder>
          getCallPhoneStateFieldBuilder() {
        if (callPhoneStateBuilder_ == null) {
          callPhoneStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CallPhoneStateProtos.CallPhoneState, CallPhoneStateProtos.CallPhoneState.Builder, CallPhoneStateProtos.CallPhoneStateOrBuilder>(
                  getCallPhoneState(),
                  getParentForChildren(),
                  isClean());
          callPhoneState_ = null;
        }
        return callPhoneStateBuilder_;
      }

      private TtPhoneSignalProtos.PhoneSignalStrength sigalStrength_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          TtPhoneSignalProtos.PhoneSignalStrength, TtPhoneSignalProtos.PhoneSignalStrength.Builder, TtPhoneSignalProtos.PhoneSignalStrengthOrBuilder> sigalStrengthBuilder_;
      /**
       * <pre>
       *手机信号强度
       * </pre>
       *
       * <code>optional .phonedata.PhoneSignalStrength sigalStrength = 2;</code>
       */
      public boolean hasSigalStrength() {
        return sigalStrengthBuilder_ != null || sigalStrength_ != null;
      }
      /**
       * <pre>
       *手机信号强度
       * </pre>
       *
       * <code>optional .phonedata.PhoneSignalStrength sigalStrength = 2;</code>
       */
      public TtPhoneSignalProtos.PhoneSignalStrength getSigalStrength() {
        if (sigalStrengthBuilder_ == null) {
          return sigalStrength_ == null ? TtPhoneSignalProtos.PhoneSignalStrength.getDefaultInstance() : sigalStrength_;
        } else {
          return sigalStrengthBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *手机信号强度
       * </pre>
       *
       * <code>optional .phonedata.PhoneSignalStrength sigalStrength = 2;</code>
       */
      public Builder setSigalStrength(TtPhoneSignalProtos.PhoneSignalStrength value) {
        if (sigalStrengthBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sigalStrength_ = value;
          onChanged();
        } else {
          sigalStrengthBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *手机信号强度
       * </pre>
       *
       * <code>optional .phonedata.PhoneSignalStrength sigalStrength = 2;</code>
       */
      public Builder setSigalStrength(
          TtPhoneSignalProtos.PhoneSignalStrength.Builder builderForValue) {
        if (sigalStrengthBuilder_ == null) {
          sigalStrength_ = builderForValue.build();
          onChanged();
        } else {
          sigalStrengthBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *手机信号强度
       * </pre>
       *
       * <code>optional .phonedata.PhoneSignalStrength sigalStrength = 2;</code>
       */
      public Builder mergeSigalStrength(TtPhoneSignalProtos.PhoneSignalStrength value) {
        if (sigalStrengthBuilder_ == null) {
          if (sigalStrength_ != null) {
            sigalStrength_ =
              TtPhoneSignalProtos.PhoneSignalStrength.newBuilder(sigalStrength_).mergeFrom(value).buildPartial();
          } else {
            sigalStrength_ = value;
          }
          onChanged();
        } else {
          sigalStrengthBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *手机信号强度
       * </pre>
       *
       * <code>optional .phonedata.PhoneSignalStrength sigalStrength = 2;</code>
       */
      public Builder clearSigalStrength() {
        if (sigalStrengthBuilder_ == null) {
          sigalStrength_ = null;
          onChanged();
        } else {
          sigalStrength_ = null;
          sigalStrengthBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *手机信号强度
       * </pre>
       *
       * <code>optional .phonedata.PhoneSignalStrength sigalStrength = 2;</code>
       */
      public TtPhoneSignalProtos.PhoneSignalStrength.Builder getSigalStrengthBuilder() {
        
        onChanged();
        return getSigalStrengthFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *手机信号强度
       * </pre>
       *
       * <code>optional .phonedata.PhoneSignalStrength sigalStrength = 2;</code>
       */
      public TtPhoneSignalProtos.PhoneSignalStrengthOrBuilder getSigalStrengthOrBuilder() {
        if (sigalStrengthBuilder_ != null) {
          return sigalStrengthBuilder_.getMessageOrBuilder();
        } else {
          return sigalStrength_ == null ?
              TtPhoneSignalProtos.PhoneSignalStrength.getDefaultInstance() : sigalStrength_;
        }
      }
      /**
       * <pre>
       *手机信号强度
       * </pre>
       *
       * <code>optional .phonedata.PhoneSignalStrength sigalStrength = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TtPhoneSignalProtos.PhoneSignalStrength, TtPhoneSignalProtos.PhoneSignalStrength.Builder, TtPhoneSignalProtos.PhoneSignalStrengthOrBuilder>
          getSigalStrengthFieldBuilder() {
        if (sigalStrengthBuilder_ == null) {
          sigalStrengthBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TtPhoneSignalProtos.PhoneSignalStrength, TtPhoneSignalProtos.PhoneSignalStrength.Builder, TtPhoneSignalProtos.PhoneSignalStrengthOrBuilder>(
                  getSigalStrength(),
                  getParentForChildren(),
                  isClean());
          sigalStrength_ = null;
        }
        return sigalStrengthBuilder_;
      }

      private TtPhoneBatteryProtos.TtPhoneBattery batterValue_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          TtPhoneBatteryProtos.TtPhoneBattery, TtPhoneBatteryProtos.TtPhoneBattery.Builder, TtPhoneBatteryProtos.TtPhoneBatteryOrBuilder> batterValueBuilder_;
      /**
       * <pre>
       *电量
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneBattery batterValue = 3;</code>
       */
      public boolean hasBatterValue() {
        return batterValueBuilder_ != null || batterValue_ != null;
      }
      /**
       * <pre>
       *电量
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneBattery batterValue = 3;</code>
       */
      public TtPhoneBatteryProtos.TtPhoneBattery getBatterValue() {
        if (batterValueBuilder_ == null) {
          return batterValue_ == null ? TtPhoneBatteryProtos.TtPhoneBattery.getDefaultInstance() : batterValue_;
        } else {
          return batterValueBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *电量
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneBattery batterValue = 3;</code>
       */
      public Builder setBatterValue(TtPhoneBatteryProtos.TtPhoneBattery value) {
        if (batterValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          batterValue_ = value;
          onChanged();
        } else {
          batterValueBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *电量
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneBattery batterValue = 3;</code>
       */
      public Builder setBatterValue(
          TtPhoneBatteryProtos.TtPhoneBattery.Builder builderForValue) {
        if (batterValueBuilder_ == null) {
          batterValue_ = builderForValue.build();
          onChanged();
        } else {
          batterValueBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *电量
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneBattery batterValue = 3;</code>
       */
      public Builder mergeBatterValue(TtPhoneBatteryProtos.TtPhoneBattery value) {
        if (batterValueBuilder_ == null) {
          if (batterValue_ != null) {
            batterValue_ =
              TtPhoneBatteryProtos.TtPhoneBattery.newBuilder(batterValue_).mergeFrom(value).buildPartial();
          } else {
            batterValue_ = value;
          }
          onChanged();
        } else {
          batterValueBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *电量
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneBattery batterValue = 3;</code>
       */
      public Builder clearBatterValue() {
        if (batterValueBuilder_ == null) {
          batterValue_ = null;
          onChanged();
        } else {
          batterValue_ = null;
          batterValueBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *电量
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneBattery batterValue = 3;</code>
       */
      public TtPhoneBatteryProtos.TtPhoneBattery.Builder getBatterValueBuilder() {
        
        onChanged();
        return getBatterValueFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *电量
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneBattery batterValue = 3;</code>
       */
      public TtPhoneBatteryProtos.TtPhoneBatteryOrBuilder getBatterValueOrBuilder() {
        if (batterValueBuilder_ != null) {
          return batterValueBuilder_.getMessageOrBuilder();
        } else {
          return batterValue_ == null ?
              TtPhoneBatteryProtos.TtPhoneBattery.getDefaultInstance() : batterValue_;
        }
      }
      /**
       * <pre>
       *电量
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneBattery batterValue = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TtPhoneBatteryProtos.TtPhoneBattery, TtPhoneBatteryProtos.TtPhoneBattery.Builder, TtPhoneBatteryProtos.TtPhoneBatteryOrBuilder>
          getBatterValueFieldBuilder() {
        if (batterValueBuilder_ == null) {
          batterValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TtPhoneBatteryProtos.TtPhoneBattery, TtPhoneBatteryProtos.TtPhoneBattery.Builder, TtPhoneBatteryProtos.TtPhoneBatteryOrBuilder>(
                  getBatterValue(),
                  getParentForChildren(),
                  isClean());
          batterValue_ = null;
        }
        return batterValueBuilder_;
      }

      private TtPhoneSimCards.TtPhoneSimCard ttPhoneSimcard_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          TtPhoneSimCards.TtPhoneSimCard, TtPhoneSimCards.TtPhoneSimCard.Builder, TtPhoneSimCards.TtPhoneSimCardOrBuilder> ttPhoneSimcardBuilder_;
      /**
       * <pre>
       *sim 卡
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneSimCard ttPhoneSimcard = 4;</code>
       */
      public boolean hasTtPhoneSimcard() {
        return ttPhoneSimcardBuilder_ != null || ttPhoneSimcard_ != null;
      }
      /**
       * <pre>
       *sim 卡
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneSimCard ttPhoneSimcard = 4;</code>
       */
      public TtPhoneSimCards.TtPhoneSimCard getTtPhoneSimcard() {
        if (ttPhoneSimcardBuilder_ == null) {
          return ttPhoneSimcard_ == null ? TtPhoneSimCards.TtPhoneSimCard.getDefaultInstance() : ttPhoneSimcard_;
        } else {
          return ttPhoneSimcardBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *sim 卡
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneSimCard ttPhoneSimcard = 4;</code>
       */
      public Builder setTtPhoneSimcard(TtPhoneSimCards.TtPhoneSimCard value) {
        if (ttPhoneSimcardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ttPhoneSimcard_ = value;
          onChanged();
        } else {
          ttPhoneSimcardBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *sim 卡
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneSimCard ttPhoneSimcard = 4;</code>
       */
      public Builder setTtPhoneSimcard(
          TtPhoneSimCards.TtPhoneSimCard.Builder builderForValue) {
        if (ttPhoneSimcardBuilder_ == null) {
          ttPhoneSimcard_ = builderForValue.build();
          onChanged();
        } else {
          ttPhoneSimcardBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *sim 卡
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneSimCard ttPhoneSimcard = 4;</code>
       */
      public Builder mergeTtPhoneSimcard(TtPhoneSimCards.TtPhoneSimCard value) {
        if (ttPhoneSimcardBuilder_ == null) {
          if (ttPhoneSimcard_ != null) {
            ttPhoneSimcard_ =
              TtPhoneSimCards.TtPhoneSimCard.newBuilder(ttPhoneSimcard_).mergeFrom(value).buildPartial();
          } else {
            ttPhoneSimcard_ = value;
          }
          onChanged();
        } else {
          ttPhoneSimcardBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *sim 卡
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneSimCard ttPhoneSimcard = 4;</code>
       */
      public Builder clearTtPhoneSimcard() {
        if (ttPhoneSimcardBuilder_ == null) {
          ttPhoneSimcard_ = null;
          onChanged();
        } else {
          ttPhoneSimcard_ = null;
          ttPhoneSimcardBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *sim 卡
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneSimCard ttPhoneSimcard = 4;</code>
       */
      public TtPhoneSimCards.TtPhoneSimCard.Builder getTtPhoneSimcardBuilder() {
        
        onChanged();
        return getTtPhoneSimcardFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *sim 卡
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneSimCard ttPhoneSimcard = 4;</code>
       */
      public TtPhoneSimCards.TtPhoneSimCardOrBuilder getTtPhoneSimcardOrBuilder() {
        if (ttPhoneSimcardBuilder_ != null) {
          return ttPhoneSimcardBuilder_.getMessageOrBuilder();
        } else {
          return ttPhoneSimcard_ == null ?
              TtPhoneSimCards.TtPhoneSimCard.getDefaultInstance() : ttPhoneSimcard_;
        }
      }
      /**
       * <pre>
       *sim 卡
       * </pre>
       *
       * <code>optional .phonedata.TtPhoneSimCard ttPhoneSimcard = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TtPhoneSimCards.TtPhoneSimCard, TtPhoneSimCards.TtPhoneSimCard.Builder, TtPhoneSimCards.TtPhoneSimCardOrBuilder>
          getTtPhoneSimcardFieldBuilder() {
        if (ttPhoneSimcardBuilder_ == null) {
          ttPhoneSimcardBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TtPhoneSimCards.TtPhoneSimCard, TtPhoneSimCards.TtPhoneSimCard.Builder, TtPhoneSimCards.TtPhoneSimCardOrBuilder>(
                  getTtPhoneSimcard(),
                  getParentForChildren(),
                  isClean());
          ttPhoneSimcard_ = null;
        }
        return ttPhoneSimcardBuilder_;
      }

      private TtPhonePositionProtos.TtPhonePosition ttPhoneGpsPosition_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          TtPhonePositionProtos.TtPhonePosition, TtPhonePositionProtos.TtPhonePosition.Builder, TtPhonePositionProtos.TtPhonePositionOrBuilder> ttPhoneGpsPositionBuilder_;
      /**
       * <pre>
       *gps
       * </pre>
       *
       * <code>optional .phonedata.TtPhonePosition ttPhoneGpsPosition = 5;</code>
       */
      public boolean hasTtPhoneGpsPosition() {
        return ttPhoneGpsPositionBuilder_ != null || ttPhoneGpsPosition_ != null;
      }
      /**
       * <pre>
       *gps
       * </pre>
       *
       * <code>optional .phonedata.TtPhonePosition ttPhoneGpsPosition = 5;</code>
       */
      public TtPhonePositionProtos.TtPhonePosition getTtPhoneGpsPosition() {
        if (ttPhoneGpsPositionBuilder_ == null) {
          return ttPhoneGpsPosition_ == null ? TtPhonePositionProtos.TtPhonePosition.getDefaultInstance() : ttPhoneGpsPosition_;
        } else {
          return ttPhoneGpsPositionBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *gps
       * </pre>
       *
       * <code>optional .phonedata.TtPhonePosition ttPhoneGpsPosition = 5;</code>
       */
      public Builder setTtPhoneGpsPosition(TtPhonePositionProtos.TtPhonePosition value) {
        if (ttPhoneGpsPositionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ttPhoneGpsPosition_ = value;
          onChanged();
        } else {
          ttPhoneGpsPositionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *gps
       * </pre>
       *
       * <code>optional .phonedata.TtPhonePosition ttPhoneGpsPosition = 5;</code>
       */
      public Builder setTtPhoneGpsPosition(
          TtPhonePositionProtos.TtPhonePosition.Builder builderForValue) {
        if (ttPhoneGpsPositionBuilder_ == null) {
          ttPhoneGpsPosition_ = builderForValue.build();
          onChanged();
        } else {
          ttPhoneGpsPositionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *gps
       * </pre>
       *
       * <code>optional .phonedata.TtPhonePosition ttPhoneGpsPosition = 5;</code>
       */
      public Builder mergeTtPhoneGpsPosition(TtPhonePositionProtos.TtPhonePosition value) {
        if (ttPhoneGpsPositionBuilder_ == null) {
          if (ttPhoneGpsPosition_ != null) {
            ttPhoneGpsPosition_ =
              TtPhonePositionProtos.TtPhonePosition.newBuilder(ttPhoneGpsPosition_).mergeFrom(value).buildPartial();
          } else {
            ttPhoneGpsPosition_ = value;
          }
          onChanged();
        } else {
          ttPhoneGpsPositionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *gps
       * </pre>
       *
       * <code>optional .phonedata.TtPhonePosition ttPhoneGpsPosition = 5;</code>
       */
      public Builder clearTtPhoneGpsPosition() {
        if (ttPhoneGpsPositionBuilder_ == null) {
          ttPhoneGpsPosition_ = null;
          onChanged();
        } else {
          ttPhoneGpsPosition_ = null;
          ttPhoneGpsPositionBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *gps
       * </pre>
       *
       * <code>optional .phonedata.TtPhonePosition ttPhoneGpsPosition = 5;</code>
       */
      public TtPhonePositionProtos.TtPhonePosition.Builder getTtPhoneGpsPositionBuilder() {
        
        onChanged();
        return getTtPhoneGpsPositionFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *gps
       * </pre>
       *
       * <code>optional .phonedata.TtPhonePosition ttPhoneGpsPosition = 5;</code>
       */
      public TtPhonePositionProtos.TtPhonePositionOrBuilder getTtPhoneGpsPositionOrBuilder() {
        if (ttPhoneGpsPositionBuilder_ != null) {
          return ttPhoneGpsPositionBuilder_.getMessageOrBuilder();
        } else {
          return ttPhoneGpsPosition_ == null ?
              TtPhonePositionProtos.TtPhonePosition.getDefaultInstance() : ttPhoneGpsPosition_;
        }
      }
      /**
       * <pre>
       *gps
       * </pre>
       *
       * <code>optional .phonedata.TtPhonePosition ttPhoneGpsPosition = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          TtPhonePositionProtos.TtPhonePosition, TtPhonePositionProtos.TtPhonePosition.Builder, TtPhonePositionProtos.TtPhonePositionOrBuilder>
          getTtPhoneGpsPositionFieldBuilder() {
        if (ttPhoneGpsPositionBuilder_ == null) {
          ttPhoneGpsPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              TtPhonePositionProtos.TtPhonePosition, TtPhonePositionProtos.TtPhonePosition.Builder, TtPhonePositionProtos.TtPhonePositionOrBuilder>(
                  getTtPhoneGpsPosition(),
                  getParentForChildren(),
                  isClean());
          ttPhoneGpsPosition_ = null;
        }
        return ttPhoneGpsPositionBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:phonedata.TimerSend)
    }

    // @@protoc_insertion_point(class_scope:phonedata.TimerSend)
    private static final TimerSend DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TimerSend();
    }

    public static TimerSend getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TimerSend>
        PARSER = new com.google.protobuf.AbstractParser<TimerSend>() {
      public TimerSend parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TimerSend(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TimerSend> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TimerSend> getParserForType() {
      return PARSER;
    }

    public TimerSend getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_phonedata_TimerSend_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_phonedata_TimerSend_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017TimerSend.proto\022\tphonedata\032\024CallPhoneS" +
      "tate.proto\032\023TtPhoneSignal.proto\032\024TtPhone" +
      "Battery.proto\032\024TtPhoneSimCard.proto\032\025TtP" +
      "honePosition.proto\"\220\002\n\tTimerSend\0221\n\016call" +
      "PhoneState\030\001 \001(\0132\031.phonedata.CallPhoneSt" +
      "ate\0225\n\rsigalStrength\030\002 \001(\0132\036.phonedata.P" +
      "honeSignalStrength\022.\n\013batterValue\030\003 \001(\0132" +
      "\031.phonedata.TtPhoneBattery\0221\n\016ttPhoneSim" +
      "card\030\004 \001(\0132\031.phonedata.TtPhoneSimCard\0226\n" +
      "\022ttPhoneGpsPosition\030\005 \001(\0132\032.phonedata.Tt",
      "PhonePositionB\"\n\017com.qzy.tt.dataB\017TimerS" +
      "endProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          CallPhoneStateProtos.getDescriptor(),
          TtPhoneSignalProtos.getDescriptor(),
          TtPhoneBatteryProtos.getDescriptor(),
          TtPhoneSimCards.getDescriptor(),
          TtPhonePositionProtos.getDescriptor(),
        }, assigner);
    internal_static_phonedata_TimerSend_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_phonedata_TimerSend_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_phonedata_TimerSend_descriptor,
        new String[] { "CallPhoneState", "SigalStrength", "BatterValue", "TtPhoneSimcard", "TtPhoneGpsPosition", });
    CallPhoneStateProtos.getDescriptor();
    TtPhoneSignalProtos.getDescriptor();
    TtPhoneBatteryProtos.getDescriptor();
    TtPhoneSimCards.getDescriptor();
    TtPhonePositionProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
