// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TtDeleSms.proto

package com.qzy.tt.data;

public final class TtDeleSmsProtos {
  private TtDeleSmsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TtDeleSmsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:phonedata.TtDeleSms)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string ip = 1;</code>
     */
    String getIp();
    /**
     * <code>optional string ip = 1;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <pre>
     *   是否删除全部
     * </pre>
     *
     * <code>optional bool isDeleAll = 2;</code>
     */
    boolean getIsDeleAll();

    /**
     * <pre>
     * 删除单个id
     * </pre>
     *
     * <code>optional int64 server_data_id = 3;</code>
     */
    long getServerDataId();

    /**
     * <pre>
     * 删除phone number 关联的所有记录
     * </pre>
     *
     * <code>optional string phonenumber = 4;</code>
     */
    String getPhonenumber();
    /**
     * <pre>
     * 删除phone number 关联的所有记录
     * </pre>
     *
     * <code>optional string phonenumber = 4;</code>
     */
    com.google.protobuf.ByteString
        getPhonenumberBytes();

    /**
     * <pre>
     * 是否 是服务端回复手机端
     * </pre>
     *
     * <code>optional bool isResponse = 5;</code>
     */
    boolean getIsResponse();

    /**
     * <pre>
     * 操作结果返回
     * </pre>
     *
     * <code>optional bool state = 6;</code>
     */
    boolean getState();
  }
  /**
   * Protobuf type {@code phonedata.TtDeleSms}
   */
  public  static final class TtDeleSms extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:phonedata.TtDeleSms)
      TtDeleSmsOrBuilder {
    // Use TtDeleSms.newBuilder() to construct.
    private TtDeleSms(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TtDeleSms() {
      ip_ = "";
      isDeleAll_ = false;
      serverDataId_ = 0L;
      phonenumber_ = "";
      isResponse_ = false;
      state_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TtDeleSms(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 16: {

              isDeleAll_ = input.readBool();
              break;
            }
            case 24: {

              serverDataId_ = input.readInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              phonenumber_ = s;
              break;
            }
            case 40: {

              isResponse_ = input.readBool();
              break;
            }
            case 48: {

              state_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qzy.tt.data.TtDeleSmsProtos.internal_static_phonedata_TtDeleSms_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qzy.tt.data.TtDeleSmsProtos.internal_static_phonedata_TtDeleSms_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms.class, com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms.Builder.class);
    }

    public static final int IP_FIELD_NUMBER = 1;
    private volatile Object ip_;
    /**
     * <code>optional string ip = 1;</code>
     */
    public String getIp() {
      Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ip = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISDELEALL_FIELD_NUMBER = 2;
    private boolean isDeleAll_;
    /**
     * <pre>
     *   是否删除全部
     * </pre>
     *
     * <code>optional bool isDeleAll = 2;</code>
     */
    public boolean getIsDeleAll() {
      return isDeleAll_;
    }

    public static final int SERVER_DATA_ID_FIELD_NUMBER = 3;
    private long serverDataId_;
    /**
     * <pre>
     * 删除单个id
     * </pre>
     *
     * <code>optional int64 server_data_id = 3;</code>
     */
    public long getServerDataId() {
      return serverDataId_;
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 4;
    private volatile Object phonenumber_;
    /**
     * <pre>
     * 删除phone number 关联的所有记录
     * </pre>
     *
     * <code>optional string phonenumber = 4;</code>
     */
    public String getPhonenumber() {
      Object ref = phonenumber_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        phonenumber_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 删除phone number 关联的所有记录
     * </pre>
     *
     * <code>optional string phonenumber = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPhonenumberBytes() {
      Object ref = phonenumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        phonenumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISRESPONSE_FIELD_NUMBER = 5;
    private boolean isResponse_;
    /**
     * <pre>
     * 是否 是服务端回复手机端
     * </pre>
     *
     * <code>optional bool isResponse = 5;</code>
     */
    public boolean getIsResponse() {
      return isResponse_;
    }

    public static final int STATE_FIELD_NUMBER = 6;
    private boolean state_;
    /**
     * <pre>
     * 操作结果返回
     * </pre>
     *
     * <code>optional bool state = 6;</code>
     */
    public boolean getState() {
      return state_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ip_);
      }
      if (isDeleAll_ != false) {
        output.writeBool(2, isDeleAll_);
      }
      if (serverDataId_ != 0L) {
        output.writeInt64(3, serverDataId_);
      }
      if (!getPhonenumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, phonenumber_);
      }
      if (isResponse_ != false) {
        output.writeBool(5, isResponse_);
      }
      if (state_ != false) {
        output.writeBool(6, state_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ip_);
      }
      if (isDeleAll_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isDeleAll_);
      }
      if (serverDataId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, serverDataId_);
      }
      if (!getPhonenumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, phonenumber_);
      }
      if (isResponse_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isResponse_);
      }
      if (state_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, state_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms)) {
        return super.equals(obj);
      }
      com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms other = (com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms) obj;

      boolean result = true;
      result = result && getIp()
          .equals(other.getIp());
      result = result && (getIsDeleAll()
          == other.getIsDeleAll());
      result = result && (getServerDataId()
          == other.getServerDataId());
      result = result && getPhonenumber()
          .equals(other.getPhonenumber());
      result = result && (getIsResponse()
          == other.getIsResponse());
      result = result && (getState()
          == other.getState());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + ISDELEALL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsDeleAll());
      hash = (37 * hash) + SERVER_DATA_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getServerDataId());
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhonenumber().hashCode();
      hash = (37 * hash) + ISRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsResponse());
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getState());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code phonedata.TtDeleSms}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:phonedata.TtDeleSms)
        com.qzy.tt.data.TtDeleSmsProtos.TtDeleSmsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qzy.tt.data.TtDeleSmsProtos.internal_static_phonedata_TtDeleSms_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qzy.tt.data.TtDeleSmsProtos.internal_static_phonedata_TtDeleSms_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms.class, com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms.Builder.class);
      }

      // Construct using com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ip_ = "";

        isDeleAll_ = false;

        serverDataId_ = 0L;

        phonenumber_ = "";

        isResponse_ = false;

        state_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qzy.tt.data.TtDeleSmsProtos.internal_static_phonedata_TtDeleSms_descriptor;
      }

      public com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms getDefaultInstanceForType() {
        return com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms.getDefaultInstance();
      }

      public com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms build() {
        com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms buildPartial() {
        com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms result = new com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms(this);
        result.ip_ = ip_;
        result.isDeleAll_ = isDeleAll_;
        result.serverDataId_ = serverDataId_;
        result.phonenumber_ = phonenumber_;
        result.isResponse_ = isResponse_;
        result.state_ = state_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms) {
          return mergeFrom((com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms other) {
        if (other == com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms.getDefaultInstance()) return this;
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getIsDeleAll() != false) {
          setIsDeleAll(other.getIsDeleAll());
        }
        if (other.getServerDataId() != 0L) {
          setServerDataId(other.getServerDataId());
        }
        if (!other.getPhonenumber().isEmpty()) {
          phonenumber_ = other.phonenumber_;
          onChanged();
        }
        if (other.getIsResponse() != false) {
          setIsResponse(other.getIsResponse());
        }
        if (other.getState() != false) {
          setState(other.getState());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object ip_ = "";
      /**
       * <code>optional string ip = 1;</code>
       */
      public String getIp() {
        Object ref = ip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder setIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder clearIp() {

        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        ip_ = value;
        onChanged();
        return this;
      }

      private boolean isDeleAll_ ;
      /**
       * <pre>
       *   是否删除全部
       * </pre>
       *
       * <code>optional bool isDeleAll = 2;</code>
       */
      public boolean getIsDeleAll() {
        return isDeleAll_;
      }
      /**
       * <pre>
       *   是否删除全部
       * </pre>
       *
       * <code>optional bool isDeleAll = 2;</code>
       */
      public Builder setIsDeleAll(boolean value) {

        isDeleAll_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *   是否删除全部
       * </pre>
       *
       * <code>optional bool isDeleAll = 2;</code>
       */
      public Builder clearIsDeleAll() {

        isDeleAll_ = false;
        onChanged();
        return this;
      }

      private long serverDataId_ ;
      /**
       * <pre>
       * 删除单个id
       * </pre>
       *
       * <code>optional int64 server_data_id = 3;</code>
       */
      public long getServerDataId() {
        return serverDataId_;
      }
      /**
       * <pre>
       * 删除单个id
       * </pre>
       *
       * <code>optional int64 server_data_id = 3;</code>
       */
      public Builder setServerDataId(long value) {

        serverDataId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 删除单个id
       * </pre>
       *
       * <code>optional int64 server_data_id = 3;</code>
       */
      public Builder clearServerDataId() {

        serverDataId_ = 0L;
        onChanged();
        return this;
      }

      private Object phonenumber_ = "";
      /**
       * <pre>
       * 删除phone number 关联的所有记录
       * </pre>
       *
       * <code>optional string phonenumber = 4;</code>
       */
      public String getPhonenumber() {
        Object ref = phonenumber_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          phonenumber_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 删除phone number 关联的所有记录
       * </pre>
       *
       * <code>optional string phonenumber = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPhonenumberBytes() {
        Object ref = phonenumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          phonenumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 删除phone number 关联的所有记录
       * </pre>
       *
       * <code>optional string phonenumber = 4;</code>
       */
      public Builder setPhonenumber(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        phonenumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 删除phone number 关联的所有记录
       * </pre>
       *
       * <code>optional string phonenumber = 4;</code>
       */
      public Builder clearPhonenumber() {

        phonenumber_ = getDefaultInstance().getPhonenumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 删除phone number 关联的所有记录
       * </pre>
       *
       * <code>optional string phonenumber = 4;</code>
       */
      public Builder setPhonenumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        phonenumber_ = value;
        onChanged();
        return this;
      }

      private boolean isResponse_ ;
      /**
       * <pre>
       * 是否 是服务端回复手机端
       * </pre>
       *
       * <code>optional bool isResponse = 5;</code>
       */
      public boolean getIsResponse() {
        return isResponse_;
      }
      /**
       * <pre>
       * 是否 是服务端回复手机端
       * </pre>
       *
       * <code>optional bool isResponse = 5;</code>
       */
      public Builder setIsResponse(boolean value) {

        isResponse_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否 是服务端回复手机端
       * </pre>
       *
       * <code>optional bool isResponse = 5;</code>
       */
      public Builder clearIsResponse() {

        isResponse_ = false;
        onChanged();
        return this;
      }

      private boolean state_ ;
      /**
       * <pre>
       * 操作结果返回
       * </pre>
       *
       * <code>optional bool state = 6;</code>
       */
      public boolean getState() {
        return state_;
      }
      /**
       * <pre>
       * 操作结果返回
       * </pre>
       *
       * <code>optional bool state = 6;</code>
       */
      public Builder setState(boolean value) {

        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作结果返回
       * </pre>
       *
       * <code>optional bool state = 6;</code>
       */
      public Builder clearState() {

        state_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:phonedata.TtDeleSms)
    }

    // @@protoc_insertion_point(class_scope:phonedata.TtDeleSms)
    private static final com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms();
    }

    public static com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TtDeleSms>
        PARSER = new com.google.protobuf.AbstractParser<TtDeleSms>() {
      public TtDeleSms parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TtDeleSms(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TtDeleSms> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TtDeleSms> getParserForType() {
      return PARSER;
    }

    public com.qzy.tt.data.TtDeleSmsProtos.TtDeleSms getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_phonedata_TtDeleSms_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_phonedata_TtDeleSms_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017TtDeleSms.proto\022\tphonedata\"z\n\tTtDeleSm" +
      "s\022\n\n\002ip\030\001 \001(\t\022\021\n\tisDeleAll\030\002 \001(\010\022\026\n\016serv" +
      "er_data_id\030\003 \001(\003\022\023\n\013phonenumber\030\004 \001(\t\022\022\n" +
      "\nisResponse\030\005 \001(\010\022\r\n\005state\030\006 \001(\010B\"\n\017com." +
      "qzy.tt.dataB\017TtDeleSmsProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_phonedata_TtDeleSms_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_phonedata_TtDeleSms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_phonedata_TtDeleSms_descriptor,
        new String[] { "Ip", "IsDeleAll", "ServerDataId", "Phonenumber", "IsResponse", "State", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
