// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TtOpenBeiDou.proto

package com.qzy.tt.data;

public final class TtOpenBeiDouProtos {
  private TtOpenBeiDouProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TtOpenBeiDouOrBuilder extends
      // @@protoc_insertion_point(interface_extends:phonedata.TtOpenBeiDou)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *请求状态
     * </pre>
     *
     * <code>optional bool request_status = 1;</code>
     */
    boolean getRequestStatus();

    /**
     * <pre>
     *响应状态
     * </pre>
     *
     * <code>optional bool response_status = 2;</code>
     */
    boolean getResponseStatus();
  }
  /**
   * Protobuf type {@code phonedata.TtOpenBeiDou}
   */
  public  static final class TtOpenBeiDou extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:phonedata.TtOpenBeiDou)
      TtOpenBeiDouOrBuilder {
    // Use TtOpenBeiDou.newBuilder() to construct.
    private TtOpenBeiDou(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TtOpenBeiDou() {
      requestStatus_ = false;
      responseStatus_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TtOpenBeiDou(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              requestStatus_ = input.readBool();
              break;
            }
            case 16: {

              responseStatus_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TtOpenBeiDouProtos.internal_static_phonedata_TtOpenBeiDou_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TtOpenBeiDouProtos.internal_static_phonedata_TtOpenBeiDou_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TtOpenBeiDou.class, Builder.class);
    }

    public static final int REQUEST_STATUS_FIELD_NUMBER = 1;
    private boolean requestStatus_;
    /**
     * <pre>
     *请求状态
     * </pre>
     *
     * <code>optional bool request_status = 1;</code>
     */
    public boolean getRequestStatus() {
      return requestStatus_;
    }

    public static final int RESPONSE_STATUS_FIELD_NUMBER = 2;
    private boolean responseStatus_;
    /**
     * <pre>
     *响应状态
     * </pre>
     *
     * <code>optional bool response_status = 2;</code>
     */
    public boolean getResponseStatus() {
      return responseStatus_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestStatus_ != false) {
        output.writeBool(1, requestStatus_);
      }
      if (responseStatus_ != false) {
        output.writeBool(2, responseStatus_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestStatus_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, requestStatus_);
      }
      if (responseStatus_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, responseStatus_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TtOpenBeiDou)) {
        return super.equals(obj);
      }
      TtOpenBeiDou other = (TtOpenBeiDou) obj;

      boolean result = true;
      result = result && (getRequestStatus()
          == other.getRequestStatus());
      result = result && (getResponseStatus()
          == other.getResponseStatus());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + REQUEST_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRequestStatus());
      hash = (37 * hash) + RESPONSE_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getResponseStatus());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TtOpenBeiDou parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TtOpenBeiDou parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TtOpenBeiDou parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TtOpenBeiDou parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TtOpenBeiDou parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TtOpenBeiDou parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TtOpenBeiDou parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TtOpenBeiDou parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TtOpenBeiDou parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TtOpenBeiDou parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TtOpenBeiDou prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code phonedata.TtOpenBeiDou}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:phonedata.TtOpenBeiDou)
        TtOpenBeiDouOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TtOpenBeiDouProtos.internal_static_phonedata_TtOpenBeiDou_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TtOpenBeiDouProtos.internal_static_phonedata_TtOpenBeiDou_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TtOpenBeiDou.class, Builder.class);
      }

      // Construct using com.qzy.tt.data.TtOpenBeiDouProtos.TtOpenBeiDou.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestStatus_ = false;

        responseStatus_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TtOpenBeiDouProtos.internal_static_phonedata_TtOpenBeiDou_descriptor;
      }

      public TtOpenBeiDou getDefaultInstanceForType() {
        return TtOpenBeiDou.getDefaultInstance();
      }

      public TtOpenBeiDou build() {
        TtOpenBeiDou result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TtOpenBeiDou buildPartial() {
        TtOpenBeiDou result = new TtOpenBeiDou(this);
        result.requestStatus_ = requestStatus_;
        result.responseStatus_ = responseStatus_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TtOpenBeiDou) {
          return mergeFrom((TtOpenBeiDou)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TtOpenBeiDou other) {
        if (other == TtOpenBeiDou.getDefaultInstance()) return this;
        if (other.getRequestStatus() != false) {
          setRequestStatus(other.getRequestStatus());
        }
        if (other.getResponseStatus() != false) {
          setResponseStatus(other.getResponseStatus());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TtOpenBeiDou parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TtOpenBeiDou) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean requestStatus_ ;
      /**
       * <pre>
       *请求状态
       * </pre>
       *
       * <code>optional bool request_status = 1;</code>
       */
      public boolean getRequestStatus() {
        return requestStatus_;
      }
      /**
       * <pre>
       *请求状态
       * </pre>
       *
       * <code>optional bool request_status = 1;</code>
       */
      public Builder setRequestStatus(boolean value) {
        
        requestStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求状态
       * </pre>
       *
       * <code>optional bool request_status = 1;</code>
       */
      public Builder clearRequestStatus() {
        
        requestStatus_ = false;
        onChanged();
        return this;
      }

      private boolean responseStatus_ ;
      /**
       * <pre>
       *响应状态
       * </pre>
       *
       * <code>optional bool response_status = 2;</code>
       */
      public boolean getResponseStatus() {
        return responseStatus_;
      }
      /**
       * <pre>
       *响应状态
       * </pre>
       *
       * <code>optional bool response_status = 2;</code>
       */
      public Builder setResponseStatus(boolean value) {
        
        responseStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *响应状态
       * </pre>
       *
       * <code>optional bool response_status = 2;</code>
       */
      public Builder clearResponseStatus() {
        
        responseStatus_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:phonedata.TtOpenBeiDou)
    }

    // @@protoc_insertion_point(class_scope:phonedata.TtOpenBeiDou)
    private static final TtOpenBeiDou DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TtOpenBeiDou();
    }

    public static TtOpenBeiDou getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TtOpenBeiDou>
        PARSER = new com.google.protobuf.AbstractParser<TtOpenBeiDou>() {
      public TtOpenBeiDou parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TtOpenBeiDou(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TtOpenBeiDou> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TtOpenBeiDou> getParserForType() {
      return PARSER;
    }

    public TtOpenBeiDou getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_phonedata_TtOpenBeiDou_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_phonedata_TtOpenBeiDou_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022TtOpenBeiDou.proto\022\tphonedata\"?\n\014TtOpe" +
      "nBeiDou\022\026\n\016request_status\030\001 \001(\010\022\027\n\017respo" +
      "nse_status\030\002 \001(\010B%\n\017com.qzy.tt.dataB\022TtO" +
      "penBeiDouProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_phonedata_TtOpenBeiDou_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_phonedata_TtOpenBeiDou_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_phonedata_TtOpenBeiDou_descriptor,
        new String[] { "RequestStatus", "ResponseStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
