// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TtPhoneConnect.proto

package com.qzy.tt.data;

public final class TtPhoneSimCards {
  private TtPhoneSimCards() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TtPhoneSimCardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:phonedata.TtPhoneSimCard)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool isSimCard = 1;</code>
     */
    boolean getIsSimCard();
  }
  /**
   * Protobuf type {@code phonedata.TtPhoneSimCard}
   */
  public  static final class TtPhoneSimCard extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:phonedata.TtPhoneSimCard)
      TtPhoneSimCardOrBuilder {
    // Use TtPhoneSimCard.newBuilder() to construct.
    private TtPhoneSimCard(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TtPhoneSimCard() {
      isSimCard_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TtPhoneSimCard(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              isSimCard_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qzy.tt.data.TtPhoneSimCards.internal_static_phonedata_TtPhoneSimCard_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qzy.tt.data.TtPhoneSimCards.internal_static_phonedata_TtPhoneSimCard_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard.class, com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard.Builder.class);
    }

    public static final int ISSIMCARD_FIELD_NUMBER = 1;
    private boolean isSimCard_;
    /**
     * <code>optional bool isSimCard = 1;</code>
     */
    public boolean getIsSimCard() {
      return isSimCard_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isSimCard_ != false) {
        output.writeBool(1, isSimCard_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isSimCard_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSimCard_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard)) {
        return super.equals(obj);
      }
      com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard other = (com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard) obj;

      boolean result = true;
      result = result && (getIsSimCard()
          == other.getIsSimCard());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ISSIMCARD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSimCard());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code phonedata.TtPhoneSimCard}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:phonedata.TtPhoneSimCard)
        com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qzy.tt.data.TtPhoneSimCards.internal_static_phonedata_TtPhoneSimCard_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qzy.tt.data.TtPhoneSimCards.internal_static_phonedata_TtPhoneSimCard_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard.class, com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard.Builder.class);
      }

      // Construct using com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        isSimCard_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qzy.tt.data.TtPhoneSimCards.internal_static_phonedata_TtPhoneSimCard_descriptor;
      }

      public com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard getDefaultInstanceForType() {
        return com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard.getDefaultInstance();
      }

      public com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard build() {
        com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard buildPartial() {
        com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard result = new com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard(this);
        result.isSimCard_ = isSimCard_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard) {
          return mergeFrom((com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard other) {
        if (other == com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard.getDefaultInstance()) return this;
        if (other.getIsSimCard() != false) {
          setIsSimCard(other.getIsSimCard());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean isSimCard_ ;
      /**
       * <code>optional bool isSimCard = 1;</code>
       */
      public boolean getIsSimCard() {
        return isSimCard_;
      }
      /**
       * <code>optional bool isSimCard = 1;</code>
       */
      public Builder setIsSimCard(boolean value) {

        isSimCard_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isSimCard = 1;</code>
       */
      public Builder clearIsSimCard() {

        isSimCard_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:phonedata.TtPhoneSimCard)
    }

    // @@protoc_insertion_point(class_scope:phonedata.TtPhoneSimCard)
    private static final com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard();
    }

    public static com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TtPhoneSimCard>
        PARSER = new com.google.protobuf.AbstractParser<TtPhoneSimCard>() {
      public TtPhoneSimCard parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TtPhoneSimCard(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TtPhoneSimCard> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TtPhoneSimCard> getParserForType() {
      return PARSER;
    }

    public com.qzy.tt.data.TtPhoneSimCards.TtPhoneSimCard getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_phonedata_TtPhoneSimCard_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_phonedata_TtPhoneSimCard_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024TtPhoneConnect.proto\022\tphonedata\"#\n\016TtP" +
      "honeSimCard\022\021\n\tisSimCard\030\001 \001(\010B\"\n\017com.qz" +
      "y.tt.dataB\017TtPhoneSimCardsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_phonedata_TtPhoneSimCard_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_phonedata_TtPhoneSimCard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_phonedata_TtPhoneSimCard_descriptor,
        new String[] { "IsSimCard", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
