// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TtPhoneUpdateResponse.proto

package com.qzy.tt.data;

public final class TtPhoneUpdateResponseProtos {
  private TtPhoneUpdateResponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UpdateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:phonedata.UpdateResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string ip = 1;</code>
     */
    String getIp();
    /**
     * <code>optional string ip = 1;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <pre>
     *是否升级标志
     * </pre>
     *
     * <code>optional bool isUpdate = 2;</code>
     */
    boolean getIsUpdate();

    /**
     * <pre>
     *传送文件完成标注
     * </pre>
     *
     * <code>optional bool isSendFileFinish = 3;</code>
     */
    boolean getIsSendFileFinish();

    /**
     * <pre>
     *升级完成标志
     * </pre>
     *
     * <code>optional bool isUpdateFinish = 4;</code>
     */
    boolean getIsUpdateFinish();
  }
  /**
   * Protobuf type {@code phonedata.UpdateResponse}
   */
  public  static final class UpdateResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:phonedata.UpdateResponse)
      UpdateResponseOrBuilder {
    // Use UpdateResponse.newBuilder() to construct.
    private UpdateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateResponse() {
      ip_ = "";
      isUpdate_ = false;
      isSendFileFinish_ = false;
      isUpdateFinish_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpdateResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 16: {

              isUpdate_ = input.readBool();
              break;
            }
            case 24: {

              isSendFileFinish_ = input.readBool();
              break;
            }
            case 32: {

              isUpdateFinish_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qzy.tt.data.TtPhoneUpdateResponseProtos.internal_static_phonedata_UpdateResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qzy.tt.data.TtPhoneUpdateResponseProtos.internal_static_phonedata_UpdateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse.class, com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse.Builder.class);
    }

    public static final int IP_FIELD_NUMBER = 1;
    private volatile Object ip_;
    /**
     * <code>optional string ip = 1;</code>
     */
    public String getIp() {
      Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ip = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISUPDATE_FIELD_NUMBER = 2;
    private boolean isUpdate_;
    /**
     * <pre>
     *是否升级标志
     * </pre>
     *
     * <code>optional bool isUpdate = 2;</code>
     */
    public boolean getIsUpdate() {
      return isUpdate_;
    }

    public static final int ISSENDFILEFINISH_FIELD_NUMBER = 3;
    private boolean isSendFileFinish_;
    /**
     * <pre>
     *传送文件完成标注
     * </pre>
     *
     * <code>optional bool isSendFileFinish = 3;</code>
     */
    public boolean getIsSendFileFinish() {
      return isSendFileFinish_;
    }

    public static final int ISUPDATEFINISH_FIELD_NUMBER = 4;
    private boolean isUpdateFinish_;
    /**
     * <pre>
     *升级完成标志
     * </pre>
     *
     * <code>optional bool isUpdateFinish = 4;</code>
     */
    public boolean getIsUpdateFinish() {
      return isUpdateFinish_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ip_);
      }
      if (isUpdate_ != false) {
        output.writeBool(2, isUpdate_);
      }
      if (isSendFileFinish_ != false) {
        output.writeBool(3, isSendFileFinish_);
      }
      if (isUpdateFinish_ != false) {
        output.writeBool(4, isUpdateFinish_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ip_);
      }
      if (isUpdate_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isUpdate_);
      }
      if (isSendFileFinish_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isSendFileFinish_);
      }
      if (isUpdateFinish_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isUpdateFinish_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse)) {
        return super.equals(obj);
      }
      com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse other = (com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse) obj;

      boolean result = true;
      result = result && getIp()
          .equals(other.getIp());
      result = result && (getIsUpdate()
          == other.getIsUpdate());
      result = result && (getIsSendFileFinish()
          == other.getIsSendFileFinish());
      result = result && (getIsUpdateFinish()
          == other.getIsUpdateFinish());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + ISUPDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsUpdate());
      hash = (37 * hash) + ISSENDFILEFINISH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSendFileFinish());
      hash = (37 * hash) + ISUPDATEFINISH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsUpdateFinish());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code phonedata.UpdateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:phonedata.UpdateResponse)
        com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qzy.tt.data.TtPhoneUpdateResponseProtos.internal_static_phonedata_UpdateResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qzy.tt.data.TtPhoneUpdateResponseProtos.internal_static_phonedata_UpdateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse.class, com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse.Builder.class);
      }

      // Construct using com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ip_ = "";

        isUpdate_ = false;

        isSendFileFinish_ = false;

        isUpdateFinish_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qzy.tt.data.TtPhoneUpdateResponseProtos.internal_static_phonedata_UpdateResponse_descriptor;
      }

      public com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse getDefaultInstanceForType() {
        return com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse.getDefaultInstance();
      }

      public com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse build() {
        com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse buildPartial() {
        com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse result = new com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse(this);
        result.ip_ = ip_;
        result.isUpdate_ = isUpdate_;
        result.isSendFileFinish_ = isSendFileFinish_;
        result.isUpdateFinish_ = isUpdateFinish_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse) {
          return mergeFrom((com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse other) {
        if (other == com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse.getDefaultInstance()) return this;
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getIsUpdate() != false) {
          setIsUpdate(other.getIsUpdate());
        }
        if (other.getIsSendFileFinish() != false) {
          setIsSendFileFinish(other.getIsSendFileFinish());
        }
        if (other.getIsUpdateFinish() != false) {
          setIsUpdateFinish(other.getIsUpdateFinish());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object ip_ = "";
      /**
       * <code>optional string ip = 1;</code>
       */
      public String getIp() {
        Object ref = ip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder setIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder clearIp() {

        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        ip_ = value;
        onChanged();
        return this;
      }

      private boolean isUpdate_ ;
      /**
       * <pre>
       *是否升级标志
       * </pre>
       *
       * <code>optional bool isUpdate = 2;</code>
       */
      public boolean getIsUpdate() {
        return isUpdate_;
      }
      /**
       * <pre>
       *是否升级标志
       * </pre>
       *
       * <code>optional bool isUpdate = 2;</code>
       */
      public Builder setIsUpdate(boolean value) {

        isUpdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否升级标志
       * </pre>
       *
       * <code>optional bool isUpdate = 2;</code>
       */
      public Builder clearIsUpdate() {

        isUpdate_ = false;
        onChanged();
        return this;
      }

      private boolean isSendFileFinish_ ;
      /**
       * <pre>
       *传送文件完成标注
       * </pre>
       *
       * <code>optional bool isSendFileFinish = 3;</code>
       */
      public boolean getIsSendFileFinish() {
        return isSendFileFinish_;
      }
      /**
       * <pre>
       *传送文件完成标注
       * </pre>
       *
       * <code>optional bool isSendFileFinish = 3;</code>
       */
      public Builder setIsSendFileFinish(boolean value) {

        isSendFileFinish_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *传送文件完成标注
       * </pre>
       *
       * <code>optional bool isSendFileFinish = 3;</code>
       */
      public Builder clearIsSendFileFinish() {

        isSendFileFinish_ = false;
        onChanged();
        return this;
      }

      private boolean isUpdateFinish_ ;
      /**
       * <pre>
       *升级完成标志
       * </pre>
       *
       * <code>optional bool isUpdateFinish = 4;</code>
       */
      public boolean getIsUpdateFinish() {
        return isUpdateFinish_;
      }
      /**
       * <pre>
       *升级完成标志
       * </pre>
       *
       * <code>optional bool isUpdateFinish = 4;</code>
       */
      public Builder setIsUpdateFinish(boolean value) {

        isUpdateFinish_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *升级完成标志
       * </pre>
       *
       * <code>optional bool isUpdateFinish = 4;</code>
       */
      public Builder clearIsUpdateFinish() {

        isUpdateFinish_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:phonedata.UpdateResponse)
    }

    // @@protoc_insertion_point(class_scope:phonedata.UpdateResponse)
    private static final com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse();
    }

    public static com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateResponse>
        PARSER = new com.google.protobuf.AbstractParser<UpdateResponse>() {
      public UpdateResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UpdateResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UpdateResponse> getParserForType() {
      return PARSER;
    }

    public com.qzy.tt.data.TtPhoneUpdateResponseProtos.UpdateResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_phonedata_UpdateResponse_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_phonedata_UpdateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033TtPhoneUpdateResponse.proto\022\tphonedata" +
      "\"`\n\016UpdateResponse\022\n\n\002ip\030\001 \001(\t\022\020\n\010isUpda" +
      "te\030\002 \001(\010\022\030\n\020isSendFileFinish\030\003 \001(\010\022\026\n\016is" +
      "UpdateFinish\030\004 \001(\010B.\n\017com.qzy.tt.dataB\033T" +
      "tPhoneUpdateResponseProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_phonedata_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_phonedata_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_phonedata_UpdateResponse_descriptor,
        new String[] { "Ip", "IsUpdate", "IsSendFileFinish", "IsUpdateFinish", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
