// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TtPhoneSignal.proto

package com.qzy.tt.data;

public final class TtPhoneSignalProtos {
  private TtPhoneSignalProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PhoneSignalStrengthOrBuilder extends
      // @@protoc_insertion_point(interface_extends:phonedata.PhoneSignalStrength)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 signalStrength = 1;</code>
     */
    int getSignalStrength();
  }
  /**
   * Protobuf type {@code phonedata.PhoneSignalStrength}
   */
  public  static final class PhoneSignalStrength extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:phonedata.PhoneSignalStrength)
      PhoneSignalStrengthOrBuilder {
    // Use PhoneSignalStrength.newBuilder() to construct.
    private PhoneSignalStrength(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PhoneSignalStrength() {
      signalStrength_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PhoneSignalStrength(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              signalStrength_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qzy.tt.data.TtPhoneSignalProtos.internal_static_phonedata_PhoneSignalStrength_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qzy.tt.data.TtPhoneSignalProtos.internal_static_phonedata_PhoneSignalStrength_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength.class, com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength.Builder.class);
    }

    public static final int SIGNALSTRENGTH_FIELD_NUMBER = 1;
    private int signalStrength_;
    /**
     * <code>optional int32 signalStrength = 1;</code>
     */
    public int getSignalStrength() {
      return signalStrength_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (signalStrength_ != 0) {
        output.writeInt32(1, signalStrength_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (signalStrength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, signalStrength_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength)) {
        return super.equals(obj);
      }
      com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength other = (com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength) obj;

      boolean result = true;
      result = result && (getSignalStrength()
          == other.getSignalStrength());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SIGNALSTRENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getSignalStrength();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code phonedata.PhoneSignalStrength}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:phonedata.PhoneSignalStrength)
        com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrengthOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qzy.tt.data.TtPhoneSignalProtos.internal_static_phonedata_PhoneSignalStrength_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qzy.tt.data.TtPhoneSignalProtos.internal_static_phonedata_PhoneSignalStrength_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength.class, com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength.Builder.class);
      }

      // Construct using com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        signalStrength_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qzy.tt.data.TtPhoneSignalProtos.internal_static_phonedata_PhoneSignalStrength_descriptor;
      }

      public com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength getDefaultInstanceForType() {
        return com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength.getDefaultInstance();
      }

      public com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength build() {
        com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength buildPartial() {
        com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength result = new com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength(this);
        result.signalStrength_ = signalStrength_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength) {
          return mergeFrom((com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength other) {
        if (other == com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength.getDefaultInstance()) return this;
        if (other.getSignalStrength() != 0) {
          setSignalStrength(other.getSignalStrength());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int signalStrength_ ;
      /**
       * <code>optional int32 signalStrength = 1;</code>
       */
      public int getSignalStrength() {
        return signalStrength_;
      }
      /**
       * <code>optional int32 signalStrength = 1;</code>
       */
      public Builder setSignalStrength(int value) {

        signalStrength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 signalStrength = 1;</code>
       */
      public Builder clearSignalStrength() {

        signalStrength_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:phonedata.PhoneSignalStrength)
    }

    // @@protoc_insertion_point(class_scope:phonedata.PhoneSignalStrength)
    private static final com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength();
    }

    public static com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PhoneSignalStrength>
        PARSER = new com.google.protobuf.AbstractParser<PhoneSignalStrength>() {
      public PhoneSignalStrength parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PhoneSignalStrength(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PhoneSignalStrength> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PhoneSignalStrength> getParserForType() {
      return PARSER;
    }

    public com.qzy.tt.data.TtPhoneSignalProtos.PhoneSignalStrength getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_phonedata_PhoneSignalStrength_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_phonedata_PhoneSignalStrength_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023TtPhoneSignal.proto\022\tphonedata\"-\n\023Phon" +
      "eSignalStrength\022\026\n\016signalStrength\030\001 \001(\005B" +
      "&\n\017com.qzy.tt.dataB\023TtPhoneSignalProtosb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_phonedata_PhoneSignalStrength_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_phonedata_PhoneSignalStrength_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_phonedata_PhoneSignalStrength_descriptor,
        new String[] { "SignalStrength", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
