// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TtPhoneUpdateSendFile.proto

package com.qzy.tt.data;

public final class TtPhoneUpdateSendFileProtos {
  private TtPhoneUpdateSendFileProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UpdateSendFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:phonedata.UpdateSendFile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string ip = 1;</code>
     */
    String getIp();
    /**
     * <code>optional string ip = 1;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>optional .phonedata.UpdateSendFile.PFile fileData = 2;</code>
     */
    boolean hasFileData();
    /**
     * <code>optional .phonedata.UpdateSendFile.PFile fileData = 2;</code>
     */
    com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile getFileData();
    /**
     * <code>optional .phonedata.UpdateSendFile.PFile fileData = 2;</code>
     */
    com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFileOrBuilder getFileDataOrBuilder();

    /**
     * <code>optional bool isSendFileFinish = 3;</code>
     */
    boolean getIsSendFileFinish();
  }
  /**
   * Protobuf type {@code phonedata.UpdateSendFile}
   */
  public  static final class UpdateSendFile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:phonedata.UpdateSendFile)
      UpdateSendFileOrBuilder {
    // Use UpdateSendFile.newBuilder() to construct.
    private UpdateSendFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateSendFile() {
      ip_ = "";
      isSendFileFinish_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpdateSendFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 18: {
              com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile.Builder subBuilder = null;
              if (fileData_ != null) {
                subBuilder = fileData_.toBuilder();
              }
              fileData_ = input.readMessage(com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fileData_);
                fileData_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              isSendFileFinish_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qzy.tt.data.TtPhoneUpdateSendFileProtos.internal_static_phonedata_UpdateSendFile_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qzy.tt.data.TtPhoneUpdateSendFileProtos.internal_static_phonedata_UpdateSendFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.class, com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.Builder.class);
    }

    public interface PFileOrBuilder extends
        // @@protoc_insertion_point(interface_extends:phonedata.UpdateSendFile.PFile)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string filename = 1;</code>
       */
      String getFilename();
      /**
       * <code>optional string filename = 1;</code>
       */
      com.google.protobuf.ByteString
          getFilenameBytes();

      /**
       * <code>optional uint32 size = 2;</code>
       */
      int getSize();

      /**
       * <code>optional bytes data = 3;</code>
       */
      com.google.protobuf.ByteString getData();
    }
    /**
     * Protobuf type {@code phonedata.UpdateSendFile.PFile}
     */
    public  static final class PFile extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:phonedata.UpdateSendFile.PFile)
        PFileOrBuilder {
      // Use PFile.newBuilder() to construct.
      private PFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PFile() {
        filename_ = "";
        size_ = 0;
        data_ = com.google.protobuf.ByteString.EMPTY;
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private PFile(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                filename_ = s;
                break;
              }
              case 16: {

                size_ = input.readUInt32();
                break;
              }
              case 26: {

                data_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qzy.tt.data.TtPhoneUpdateSendFileProtos.internal_static_phonedata_UpdateSendFile_PFile_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qzy.tt.data.TtPhoneUpdateSendFileProtos.internal_static_phonedata_UpdateSendFile_PFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile.class, com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile.Builder.class);
      }

      public static final int FILENAME_FIELD_NUMBER = 1;
      private volatile Object filename_;
      /**
       * <code>optional string filename = 1;</code>
       */
      public String getFilename() {
        Object ref = filename_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          filename_ = s;
          return s;
        }
      }
      /**
       * <code>optional string filename = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SIZE_FIELD_NUMBER = 2;
      private int size_;
      /**
       * <code>optional uint32 size = 2;</code>
       */
      public int getSize() {
        return size_;
      }

      public static final int DATA_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString data_;
      /**
       * <code>optional bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getFilenameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filename_);
        }
        if (size_ != 0) {
          output.writeUInt32(2, size_);
        }
        if (!data_.isEmpty()) {
          output.writeBytes(3, data_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getFilenameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filename_);
        }
        if (size_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, size_);
        }
        if (!data_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, data_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile)) {
          return super.equals(obj);
        }
        com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile other = (com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile) obj;

        boolean result = true;
        result = result && getFilename()
            .equals(other.getFilename());
        result = result && (getSize()
            == other.getSize());
        result = result && getData()
            .equals(other.getData());
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + FILENAME_FIELD_NUMBER;
        hash = (53 * hash) + getFilename().hashCode();
        hash = (37 * hash) + SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getSize();
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code phonedata.UpdateSendFile.PFile}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:phonedata.UpdateSendFile.PFile)
          com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFileOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.qzy.tt.data.TtPhoneUpdateSendFileProtos.internal_static_phonedata_UpdateSendFile_PFile_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.qzy.tt.data.TtPhoneUpdateSendFileProtos.internal_static_phonedata_UpdateSendFile_PFile_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile.class, com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile.Builder.class);
        }

        // Construct using com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          filename_ = "";

          size_ = 0;

          data_ = com.google.protobuf.ByteString.EMPTY;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.qzy.tt.data.TtPhoneUpdateSendFileProtos.internal_static_phonedata_UpdateSendFile_PFile_descriptor;
        }

        public com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile getDefaultInstanceForType() {
          return com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile.getDefaultInstance();
        }

        public com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile build() {
          com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile buildPartial() {
          com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile result = new com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile(this);
          result.filename_ = filename_;
          result.size_ = size_;
          result.data_ = data_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile) {
            return mergeFrom((com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile other) {
          if (other == com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile.getDefaultInstance()) return this;
          if (!other.getFilename().isEmpty()) {
            filename_ = other.filename_;
            onChanged();
          }
          if (other.getSize() != 0) {
            setSize(other.getSize());
          }
          if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
            setData(other.getData());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private Object filename_ = "";
        /**
         * <code>optional string filename = 1;</code>
         */
        public String getFilename() {
          Object ref = filename_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            filename_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string filename = 1;</code>
         */
        public com.google.protobuf.ByteString
            getFilenameBytes() {
          Object ref = filename_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            filename_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string filename = 1;</code>
         */
        public Builder setFilename(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }

          filename_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string filename = 1;</code>
         */
        public Builder clearFilename() {

          filename_ = getDefaultInstance().getFilename();
          onChanged();
          return this;
        }
        /**
         * <code>optional string filename = 1;</code>
         */
        public Builder setFilenameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

          filename_ = value;
          onChanged();
          return this;
        }

        private int size_ ;
        /**
         * <code>optional uint32 size = 2;</code>
         */
        public int getSize() {
          return size_;
        }
        /**
         * <code>optional uint32 size = 2;</code>
         */
        public Builder setSize(int value) {

          size_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 size = 2;</code>
         */
        public Builder clearSize() {

          size_ = 0;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes data = 3;</code>
         */
        public com.google.protobuf.ByteString getData() {
          return data_;
        }
        /**
         * <code>optional bytes data = 3;</code>
         */
        public Builder setData(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }

          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes data = 3;</code>
         */
        public Builder clearData() {

          data_ = getDefaultInstance().getData();
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:phonedata.UpdateSendFile.PFile)
      }

      // @@protoc_insertion_point(class_scope:phonedata.UpdateSendFile.PFile)
      private static final com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile();
      }

      public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PFile>
          PARSER = new com.google.protobuf.AbstractParser<PFile>() {
        public PFile parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new PFile(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<PFile> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<PFile> getParserForType() {
        return PARSER;
      }

      public com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int IP_FIELD_NUMBER = 1;
    private volatile Object ip_;
    /**
     * <code>optional string ip = 1;</code>
     */
    public String getIp() {
      Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ip = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILEDATA_FIELD_NUMBER = 2;
    private com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile fileData_;
    /**
     * <code>optional .phonedata.UpdateSendFile.PFile fileData = 2;</code>
     */
    public boolean hasFileData() {
      return fileData_ != null;
    }
    /**
     * <code>optional .phonedata.UpdateSendFile.PFile fileData = 2;</code>
     */
    public com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile getFileData() {
      return fileData_ == null ? com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile.getDefaultInstance() : fileData_;
    }
    /**
     * <code>optional .phonedata.UpdateSendFile.PFile fileData = 2;</code>
     */
    public com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFileOrBuilder getFileDataOrBuilder() {
      return getFileData();
    }

    public static final int ISSENDFILEFINISH_FIELD_NUMBER = 3;
    private boolean isSendFileFinish_;
    /**
     * <code>optional bool isSendFileFinish = 3;</code>
     */
    public boolean getIsSendFileFinish() {
      return isSendFileFinish_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ip_);
      }
      if (fileData_ != null) {
        output.writeMessage(2, getFileData());
      }
      if (isSendFileFinish_ != false) {
        output.writeBool(3, isSendFileFinish_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ip_);
      }
      if (fileData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFileData());
      }
      if (isSendFileFinish_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isSendFileFinish_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile)) {
        return super.equals(obj);
      }
      com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile other = (com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile) obj;

      boolean result = true;
      result = result && getIp()
          .equals(other.getIp());
      result = result && (hasFileData() == other.hasFileData());
      if (hasFileData()) {
        result = result && getFileData()
            .equals(other.getFileData());
      }
      result = result && (getIsSendFileFinish()
          == other.getIsSendFileFinish());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      if (hasFileData()) {
        hash = (37 * hash) + FILEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getFileData().hashCode();
      }
      hash = (37 * hash) + ISSENDFILEFINISH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSendFileFinish());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code phonedata.UpdateSendFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:phonedata.UpdateSendFile)
        com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qzy.tt.data.TtPhoneUpdateSendFileProtos.internal_static_phonedata_UpdateSendFile_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qzy.tt.data.TtPhoneUpdateSendFileProtos.internal_static_phonedata_UpdateSendFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.class, com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.Builder.class);
      }

      // Construct using com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ip_ = "";

        if (fileDataBuilder_ == null) {
          fileData_ = null;
        } else {
          fileData_ = null;
          fileDataBuilder_ = null;
        }
        isSendFileFinish_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qzy.tt.data.TtPhoneUpdateSendFileProtos.internal_static_phonedata_UpdateSendFile_descriptor;
      }

      public com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile getDefaultInstanceForType() {
        return com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.getDefaultInstance();
      }

      public com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile build() {
        com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile buildPartial() {
        com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile result = new com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile(this);
        result.ip_ = ip_;
        if (fileDataBuilder_ == null) {
          result.fileData_ = fileData_;
        } else {
          result.fileData_ = fileDataBuilder_.build();
        }
        result.isSendFileFinish_ = isSendFileFinish_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile) {
          return mergeFrom((com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile other) {
        if (other == com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.getDefaultInstance()) return this;
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasFileData()) {
          mergeFileData(other.getFileData());
        }
        if (other.getIsSendFileFinish() != false) {
          setIsSendFileFinish(other.getIsSendFileFinish());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object ip_ = "";
      /**
       * <code>optional string ip = 1;</code>
       */
      public String getIp() {
        Object ref = ip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder setIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder clearIp() {

        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        ip_ = value;
        onChanged();
        return this;
      }

      private com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile fileData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          PFile, PFile.Builder, PFileOrBuilder> fileDataBuilder_;
      /**
       * <code>optional .phonedata.UpdateSendFile.PFile fileData = 2;</code>
       */
      public boolean hasFileData() {
        return fileDataBuilder_ != null || fileData_ != null;
      }
      /**
       * <code>optional .phonedata.UpdateSendFile.PFile fileData = 2;</code>
       */
      public com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile getFileData() {
        if (fileDataBuilder_ == null) {
          return fileData_ == null ? com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile.getDefaultInstance() : fileData_;
        } else {
          return fileDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .phonedata.UpdateSendFile.PFile fileData = 2;</code>
       */
      public Builder setFileData(com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile value) {
        if (fileDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fileData_ = value;
          onChanged();
        } else {
          fileDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .phonedata.UpdateSendFile.PFile fileData = 2;</code>
       */
      public Builder setFileData(
          com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile.Builder builderForValue) {
        if (fileDataBuilder_ == null) {
          fileData_ = builderForValue.build();
          onChanged();
        } else {
          fileDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .phonedata.UpdateSendFile.PFile fileData = 2;</code>
       */
      public Builder mergeFileData(com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile value) {
        if (fileDataBuilder_ == null) {
          if (fileData_ != null) {
            fileData_ =
              com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile.newBuilder(fileData_).mergeFrom(value).buildPartial();
          } else {
            fileData_ = value;
          }
          onChanged();
        } else {
          fileDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .phonedata.UpdateSendFile.PFile fileData = 2;</code>
       */
      public Builder clearFileData() {
        if (fileDataBuilder_ == null) {
          fileData_ = null;
          onChanged();
        } else {
          fileData_ = null;
          fileDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .phonedata.UpdateSendFile.PFile fileData = 2;</code>
       */
      public com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile.Builder getFileDataBuilder() {

        onChanged();
        return getFileDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .phonedata.UpdateSendFile.PFile fileData = 2;</code>
       */
      public com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFileOrBuilder getFileDataOrBuilder() {
        if (fileDataBuilder_ != null) {
          return fileDataBuilder_.getMessageOrBuilder();
        } else {
          return fileData_ == null ?
              com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile.PFile.getDefaultInstance() : fileData_;
        }
      }
      /**
       * <code>optional .phonedata.UpdateSendFile.PFile fileData = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          PFile, PFile.Builder, PFileOrBuilder>
          getFileDataFieldBuilder() {
        if (fileDataBuilder_ == null) {
          fileDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              PFile, PFile.Builder, PFileOrBuilder>(
                  getFileData(),
                  getParentForChildren(),
                  isClean());
          fileData_ = null;
        }
        return fileDataBuilder_;
      }

      private boolean isSendFileFinish_ ;
      /**
       * <code>optional bool isSendFileFinish = 3;</code>
       */
      public boolean getIsSendFileFinish() {
        return isSendFileFinish_;
      }
      /**
       * <code>optional bool isSendFileFinish = 3;</code>
       */
      public Builder setIsSendFileFinish(boolean value) {

        isSendFileFinish_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isSendFileFinish = 3;</code>
       */
      public Builder clearIsSendFileFinish() {

        isSendFileFinish_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:phonedata.UpdateSendFile)
    }

    // @@protoc_insertion_point(class_scope:phonedata.UpdateSendFile)
    private static final com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile();
    }

    public static com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateSendFile>
        PARSER = new com.google.protobuf.AbstractParser<UpdateSendFile>() {
      public UpdateSendFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UpdateSendFile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateSendFile> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UpdateSendFile> getParserForType() {
      return PARSER;
    }

    public com.qzy.tt.data.TtPhoneUpdateSendFileProtos.UpdateSendFile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_phonedata_UpdateSendFile_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_phonedata_UpdateSendFile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_phonedata_UpdateSendFile_PFile_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_phonedata_UpdateSendFile_PFile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033TtPhoneUpdateSendFile.proto\022\tphonedata" +
      "\"\240\001\n\016UpdateSendFile\022\n\n\002ip\030\001 \001(\t\0221\n\010fileD" +
      "ata\030\002 \001(\0132\037.phonedata.UpdateSendFile.PFi" +
      "le\022\030\n\020isSendFileFinish\030\003 \001(\010\0325\n\005PFile\022\020\n" +
      "\010filename\030\001 \001(\t\022\014\n\004size\030\002 \001(\r\022\014\n\004data\030\003 " +
      "\001(\014B.\n\017com.qzy.tt.dataB\033TtPhoneUpdateSen" +
      "dFileProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_phonedata_UpdateSendFile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_phonedata_UpdateSendFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_phonedata_UpdateSendFile_descriptor,
        new String[] { "Ip", "FileData", "IsSendFileFinish", });
    internal_static_phonedata_UpdateSendFile_PFile_descriptor =
      internal_static_phonedata_UpdateSendFile_descriptor.getNestedTypes().get(0);
    internal_static_phonedata_UpdateSendFile_PFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_phonedata_UpdateSendFile_PFile_descriptor,
        new String[] { "Filename", "Size", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
