// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TtShortMessage.proto

package com.qzy.tt.data;

public final class TtShortMessageProtos {
  private TtShortMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TtShortMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:phonedata.TtShortMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool request = 1;</code>
     */
    boolean getRequest();

    /**
     * <code>optional bool response = 2;</code>
     */
    boolean getResponse();

    /**
     * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
     */
    java.util.List<TtShortMessage.ShortMessage>
        getShortMessageList();
    /**
     * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
     */
    com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage getShortMessage(int index);
    /**
     * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
     */
    int getShortMessageCount();
    /**
     * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
     */
    java.util.List<? extends TtShortMessage.ShortMessageOrBuilder>
        getShortMessageOrBuilderList();
    /**
     * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
     */
    com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessageOrBuilder getShortMessageOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code phonedata.TtShortMessage}
   */
  public  static final class TtShortMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:phonedata.TtShortMessage)
      TtShortMessageOrBuilder {
    // Use TtShortMessage.newBuilder() to construct.
    private TtShortMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TtShortMessage() {
      request_ = false;
      response_ = false;
      shortMessage_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TtShortMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              request_ = input.readBool();
              break;
            }
            case 16: {

              response_ = input.readBool();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                shortMessage_ = new java.util.ArrayList<ShortMessage>();
                mutable_bitField0_ |= 0x00000004;
              }
              shortMessage_.add(
                  input.readMessage(com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          shortMessage_ = java.util.Collections.unmodifiableList(shortMessage_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qzy.tt.data.TtShortMessageProtos.internal_static_phonedata_TtShortMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qzy.tt.data.TtShortMessageProtos.internal_static_phonedata_TtShortMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.class, com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.Builder.class);
    }

    public interface ShortMessageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:phonedata.TtShortMessage.ShortMessage)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string numberPhone = 1;</code>
       */
      String getNumberPhone();
      /**
       * <code>optional string numberPhone = 1;</code>
       */
      com.google.protobuf.ByteString
          getNumberPhoneBytes();

      /**
       * <code>optional string message = 2;</code>
       */
      String getMessage();
      /**
       * <code>optional string message = 2;</code>
       */
      com.google.protobuf.ByteString
          getMessageBytes();

      /**
       * <code>optional string time = 3;</code>
       */
      String getTime();
      /**
       * <code>optional string time = 3;</code>
       */
      com.google.protobuf.ByteString
          getTimeBytes();

      /**
       * <code>optional int32 type = 4;</code>
       */
      int getType();

      /**
       * <code>optional string name = 5;</code>
       */
      String getName();
      /**
       * <code>optional string name = 5;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * Protobuf type {@code phonedata.TtShortMessage.ShortMessage}
     */
    public  static final class ShortMessage extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:phonedata.TtShortMessage.ShortMessage)
        ShortMessageOrBuilder {
      // Use ShortMessage.newBuilder() to construct.
      private ShortMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ShortMessage() {
        numberPhone_ = "";
        message_ = "";
        time_ = "";
        type_ = 0;
        name_ = "";
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private ShortMessage(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                numberPhone_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                message_ = s;
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                time_ = s;
                break;
              }
              case 32: {

                type_ = input.readInt32();
                break;
              }
              case 42: {
                String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qzy.tt.data.TtShortMessageProtos.internal_static_phonedata_TtShortMessage_ShortMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qzy.tt.data.TtShortMessageProtos.internal_static_phonedata_TtShortMessage_ShortMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.class, com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.Builder.class);
      }

      public static final int NUMBERPHONE_FIELD_NUMBER = 1;
      private volatile Object numberPhone_;
      /**
       * <code>optional string numberPhone = 1;</code>
       */
      public String getNumberPhone() {
        Object ref = numberPhone_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          numberPhone_ = s;
          return s;
        }
      }
      /**
       * <code>optional string numberPhone = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumberPhoneBytes() {
        Object ref = numberPhone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          numberPhone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int MESSAGE_FIELD_NUMBER = 2;
      private volatile Object message_;
      /**
       * <code>optional string message = 2;</code>
       */
      public String getMessage() {
        Object ref = message_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TIME_FIELD_NUMBER = 3;
      private volatile Object time_;
      /**
       * <code>optional string time = 3;</code>
       */
      public String getTime() {
        Object ref = time_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          time_ = s;
          return s;
        }
      }
      /**
       * <code>optional string time = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 4;
      private int type_;
      /**
       * <code>optional int32 type = 4;</code>
       */
      public int getType() {
        return type_;
      }

      public static final int NAME_FIELD_NUMBER = 5;
      private volatile Object name_;
      /**
       * <code>optional string name = 5;</code>
       */
      public String getName() {
        Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>optional string name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNumberPhoneBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, numberPhone_);
        }
        if (!getMessageBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
        }
        if (!getTimeBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, time_);
        }
        if (type_ != 0) {
          output.writeInt32(4, type_);
        }
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 5, name_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNumberPhoneBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, numberPhone_);
        }
        if (!getMessageBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
        }
        if (!getTimeBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, time_);
        }
        if (type_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, type_);
        }
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, name_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage)) {
          return super.equals(obj);
        }
        com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage other = (com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage) obj;

        boolean result = true;
        result = result && getNumberPhone()
            .equals(other.getNumberPhone());
        result = result && getMessage()
            .equals(other.getMessage());
        result = result && getTime()
            .equals(other.getTime());
        result = result && (getType()
            == other.getType());
        result = result && getName()
            .equals(other.getName());
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + NUMBERPHONE_FIELD_NUMBER;
        hash = (53 * hash) + getNumberPhone().hashCode();
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code phonedata.TtShortMessage.ShortMessage}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:phonedata.TtShortMessage.ShortMessage)
          com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.qzy.tt.data.TtShortMessageProtos.internal_static_phonedata_TtShortMessage_ShortMessage_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.qzy.tt.data.TtShortMessageProtos.internal_static_phonedata_TtShortMessage_ShortMessage_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.class, com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.Builder.class);
        }

        // Construct using com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          numberPhone_ = "";

          message_ = "";

          time_ = "";

          type_ = 0;

          name_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.qzy.tt.data.TtShortMessageProtos.internal_static_phonedata_TtShortMessage_ShortMessage_descriptor;
        }

        public com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage getDefaultInstanceForType() {
          return com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.getDefaultInstance();
        }

        public com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage build() {
          com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage buildPartial() {
          com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage result = new com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage(this);
          result.numberPhone_ = numberPhone_;
          result.message_ = message_;
          result.time_ = time_;
          result.type_ = type_;
          result.name_ = name_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage) {
            return mergeFrom((com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage other) {
          if (other == com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.getDefaultInstance()) return this;
          if (!other.getNumberPhone().isEmpty()) {
            numberPhone_ = other.numberPhone_;
            onChanged();
          }
          if (!other.getMessage().isEmpty()) {
            message_ = other.message_;
            onChanged();
          }
          if (!other.getTime().isEmpty()) {
            time_ = other.time_;
            onChanged();
          }
          if (other.getType() != 0) {
            setType(other.getType());
          }
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private Object numberPhone_ = "";
        /**
         * <code>optional string numberPhone = 1;</code>
         */
        public String getNumberPhone() {
          Object ref = numberPhone_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            numberPhone_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string numberPhone = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNumberPhoneBytes() {
          Object ref = numberPhone_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            numberPhone_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string numberPhone = 1;</code>
         */
        public Builder setNumberPhone(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }

          numberPhone_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string numberPhone = 1;</code>
         */
        public Builder clearNumberPhone() {

          numberPhone_ = getDefaultInstance().getNumberPhone();
          onChanged();
          return this;
        }
        /**
         * <code>optional string numberPhone = 1;</code>
         */
        public Builder setNumberPhoneBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

          numberPhone_ = value;
          onChanged();
          return this;
        }

        private Object message_ = "";
        /**
         * <code>optional string message = 2;</code>
         */
        public String getMessage() {
          Object ref = message_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            message_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public com.google.protobuf.ByteString
            getMessageBytes() {
          Object ref = message_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            message_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public Builder setMessage(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }

          message_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public Builder clearMessage() {

          message_ = getDefaultInstance().getMessage();
          onChanged();
          return this;
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public Builder setMessageBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

          message_ = value;
          onChanged();
          return this;
        }

        private Object time_ = "";
        /**
         * <code>optional string time = 3;</code>
         */
        public String getTime() {
          Object ref = time_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            time_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string time = 3;</code>
         */
        public com.google.protobuf.ByteString
            getTimeBytes() {
          Object ref = time_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            time_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string time = 3;</code>
         */
        public Builder setTime(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }

          time_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string time = 3;</code>
         */
        public Builder clearTime() {

          time_ = getDefaultInstance().getTime();
          onChanged();
          return this;
        }
        /**
         * <code>optional string time = 3;</code>
         */
        public Builder setTimeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

          time_ = value;
          onChanged();
          return this;
        }

        private int type_ ;
        /**
         * <code>optional int32 type = 4;</code>
         */
        public int getType() {
          return type_;
        }
        /**
         * <code>optional int32 type = 4;</code>
         */
        public Builder setType(int value) {

          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 type = 4;</code>
         */
        public Builder clearType() {

          type_ = 0;
          onChanged();
          return this;
        }

        private Object name_ = "";
        /**
         * <code>optional string name = 5;</code>
         */
        public String getName() {
          Object ref = name_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string name = 5;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string name = 5;</code>
         */
        public Builder setName(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }

          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 5;</code>
         */
        public Builder clearName() {

          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 5;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

          name_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:phonedata.TtShortMessage.ShortMessage)
      }

      // @@protoc_insertion_point(class_scope:phonedata.TtShortMessage.ShortMessage)
      private static final com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage();
      }

      public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ShortMessage>
          PARSER = new com.google.protobuf.AbstractParser<ShortMessage>() {
        public ShortMessage parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new ShortMessage(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ShortMessage> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<ShortMessage> getParserForType() {
        return PARSER;
      }

      public com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private boolean request_;
    /**
     * <code>optional bool request = 1;</code>
     */
    public boolean getRequest() {
      return request_;
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private boolean response_;
    /**
     * <code>optional bool response = 2;</code>
     */
    public boolean getResponse() {
      return response_;
    }

    public static final int SHORTMESSAGE_FIELD_NUMBER = 3;
    private java.util.List<ShortMessage> shortMessage_;
    /**
     * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
     */
    public java.util.List<ShortMessage> getShortMessageList() {
      return shortMessage_;
    }
    /**
     * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
     */
    public java.util.List<? extends ShortMessageOrBuilder>
        getShortMessageOrBuilderList() {
      return shortMessage_;
    }
    /**
     * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
     */
    public int getShortMessageCount() {
      return shortMessage_.size();
    }
    /**
     * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
     */
    public com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage getShortMessage(int index) {
      return shortMessage_.get(index);
    }
    /**
     * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
     */
    public com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessageOrBuilder getShortMessageOrBuilder(
        int index) {
      return shortMessage_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != false) {
        output.writeBool(1, request_);
      }
      if (response_ != false) {
        output.writeBool(2, response_);
      }
      for (int i = 0; i < shortMessage_.size(); i++) {
        output.writeMessage(3, shortMessage_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, request_);
      }
      if (response_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, response_);
      }
      for (int i = 0; i < shortMessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, shortMessage_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qzy.tt.data.TtShortMessageProtos.TtShortMessage)) {
        return super.equals(obj);
      }
      com.qzy.tt.data.TtShortMessageProtos.TtShortMessage other = (com.qzy.tt.data.TtShortMessageProtos.TtShortMessage) obj;

      boolean result = true;
      result = result && (getRequest()
          == other.getRequest());
      result = result && (getResponse()
          == other.getResponse());
      result = result && getShortMessageList()
          .equals(other.getShortMessageList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRequest());
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getResponse());
      if (getShortMessageCount() > 0) {
        hash = (37 * hash) + SHORTMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getShortMessageList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.qzy.tt.data.TtShortMessageProtos.TtShortMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code phonedata.TtShortMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:phonedata.TtShortMessage)
        com.qzy.tt.data.TtShortMessageProtos.TtShortMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qzy.tt.data.TtShortMessageProtos.internal_static_phonedata_TtShortMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qzy.tt.data.TtShortMessageProtos.internal_static_phonedata_TtShortMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.class, com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.Builder.class);
      }

      // Construct using com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getShortMessageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        request_ = false;

        response_ = false;

        if (shortMessageBuilder_ == null) {
          shortMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          shortMessageBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qzy.tt.data.TtShortMessageProtos.internal_static_phonedata_TtShortMessage_descriptor;
      }

      public com.qzy.tt.data.TtShortMessageProtos.TtShortMessage getDefaultInstanceForType() {
        return com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.getDefaultInstance();
      }

      public com.qzy.tt.data.TtShortMessageProtos.TtShortMessage build() {
        com.qzy.tt.data.TtShortMessageProtos.TtShortMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qzy.tt.data.TtShortMessageProtos.TtShortMessage buildPartial() {
        com.qzy.tt.data.TtShortMessageProtos.TtShortMessage result = new com.qzy.tt.data.TtShortMessageProtos.TtShortMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.request_ = request_;
        result.response_ = response_;
        if (shortMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            shortMessage_ = java.util.Collections.unmodifiableList(shortMessage_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.shortMessage_ = shortMessage_;
        } else {
          result.shortMessage_ = shortMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qzy.tt.data.TtShortMessageProtos.TtShortMessage) {
          return mergeFrom((com.qzy.tt.data.TtShortMessageProtos.TtShortMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qzy.tt.data.TtShortMessageProtos.TtShortMessage other) {
        if (other == com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.getDefaultInstance()) return this;
        if (other.getRequest() != false) {
          setRequest(other.getRequest());
        }
        if (other.getResponse() != false) {
          setResponse(other.getResponse());
        }
        if (shortMessageBuilder_ == null) {
          if (!other.shortMessage_.isEmpty()) {
            if (shortMessage_.isEmpty()) {
              shortMessage_ = other.shortMessage_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureShortMessageIsMutable();
              shortMessage_.addAll(other.shortMessage_);
            }
            onChanged();
          }
        } else {
          if (!other.shortMessage_.isEmpty()) {
            if (shortMessageBuilder_.isEmpty()) {
              shortMessageBuilder_.dispose();
              shortMessageBuilder_ = null;
              shortMessage_ = other.shortMessage_;
              bitField0_ = (bitField0_ & ~0x00000004);
              shortMessageBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getShortMessageFieldBuilder() : null;
            } else {
              shortMessageBuilder_.addAllMessages(other.shortMessage_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qzy.tt.data.TtShortMessageProtos.TtShortMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qzy.tt.data.TtShortMessageProtos.TtShortMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean request_ ;
      /**
       * <code>optional bool request = 1;</code>
       */
      public boolean getRequest() {
        return request_;
      }
      /**
       * <code>optional bool request = 1;</code>
       */
      public Builder setRequest(boolean value) {

        request_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool request = 1;</code>
       */
      public Builder clearRequest() {

        request_ = false;
        onChanged();
        return this;
      }

      private boolean response_ ;
      /**
       * <code>optional bool response = 2;</code>
       */
      public boolean getResponse() {
        return response_;
      }
      /**
       * <code>optional bool response = 2;</code>
       */
      public Builder setResponse(boolean value) {

        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool response = 2;</code>
       */
      public Builder clearResponse() {

        response_ = false;
        onChanged();
        return this;
      }

      private java.util.List<ShortMessage> shortMessage_ =
        java.util.Collections.emptyList();
      private void ensureShortMessageIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          shortMessage_ = new java.util.ArrayList<ShortMessage>(shortMessage_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ShortMessage, ShortMessage.Builder, ShortMessageOrBuilder> shortMessageBuilder_;

      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public java.util.List<ShortMessage> getShortMessageList() {
        if (shortMessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(shortMessage_);
        } else {
          return shortMessageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public int getShortMessageCount() {
        if (shortMessageBuilder_ == null) {
          return shortMessage_.size();
        } else {
          return shortMessageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage getShortMessage(int index) {
        if (shortMessageBuilder_ == null) {
          return shortMessage_.get(index);
        } else {
          return shortMessageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public Builder setShortMessage(
          int index, com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage value) {
        if (shortMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShortMessageIsMutable();
          shortMessage_.set(index, value);
          onChanged();
        } else {
          shortMessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public Builder setShortMessage(
          int index, com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.Builder builderForValue) {
        if (shortMessageBuilder_ == null) {
          ensureShortMessageIsMutable();
          shortMessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          shortMessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public Builder addShortMessage(com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage value) {
        if (shortMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShortMessageIsMutable();
          shortMessage_.add(value);
          onChanged();
        } else {
          shortMessageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public Builder addShortMessage(
          int index, com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage value) {
        if (shortMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShortMessageIsMutable();
          shortMessage_.add(index, value);
          onChanged();
        } else {
          shortMessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public Builder addShortMessage(
          com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.Builder builderForValue) {
        if (shortMessageBuilder_ == null) {
          ensureShortMessageIsMutable();
          shortMessage_.add(builderForValue.build());
          onChanged();
        } else {
          shortMessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public Builder addShortMessage(
          int index, com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.Builder builderForValue) {
        if (shortMessageBuilder_ == null) {
          ensureShortMessageIsMutable();
          shortMessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          shortMessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public Builder addAllShortMessage(
          Iterable<? extends ShortMessage> values) {
        if (shortMessageBuilder_ == null) {
          ensureShortMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, shortMessage_);
          onChanged();
        } else {
          shortMessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public Builder clearShortMessage() {
        if (shortMessageBuilder_ == null) {
          shortMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          shortMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public Builder removeShortMessage(int index) {
        if (shortMessageBuilder_ == null) {
          ensureShortMessageIsMutable();
          shortMessage_.remove(index);
          onChanged();
        } else {
          shortMessageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.Builder getShortMessageBuilder(
          int index) {
        return getShortMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessageOrBuilder getShortMessageOrBuilder(
          int index) {
        if (shortMessageBuilder_ == null) {
          return shortMessage_.get(index);  } else {
          return shortMessageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public java.util.List<? extends ShortMessageOrBuilder>
           getShortMessageOrBuilderList() {
        if (shortMessageBuilder_ != null) {
          return shortMessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(shortMessage_);
        }
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.Builder addShortMessageBuilder() {
        return getShortMessageFieldBuilder().addBuilder(
            com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.Builder addShortMessageBuilder(
          int index) {
        return getShortMessageFieldBuilder().addBuilder(
            index, com.qzy.tt.data.TtShortMessageProtos.TtShortMessage.ShortMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .phonedata.TtShortMessage.ShortMessage shortMessage = 3;</code>
       */
      public java.util.List<ShortMessage.Builder>
           getShortMessageBuilderList() {
        return getShortMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ShortMessage, ShortMessage.Builder, ShortMessageOrBuilder>
          getShortMessageFieldBuilder() {
        if (shortMessageBuilder_ == null) {
          shortMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ShortMessage, ShortMessage.Builder, ShortMessageOrBuilder>(
                  shortMessage_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          shortMessage_ = null;
        }
        return shortMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:phonedata.TtShortMessage)
    }

    // @@protoc_insertion_point(class_scope:phonedata.TtShortMessage)
    private static final com.qzy.tt.data.TtShortMessageProtos.TtShortMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.qzy.tt.data.TtShortMessageProtos.TtShortMessage();
    }

    public static com.qzy.tt.data.TtShortMessageProtos.TtShortMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TtShortMessage>
        PARSER = new com.google.protobuf.AbstractParser<TtShortMessage>() {
      public TtShortMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TtShortMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TtShortMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TtShortMessage> getParserForType() {
      return PARSER;
    }

    public com.qzy.tt.data.TtShortMessageProtos.TtShortMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_phonedata_TtShortMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_phonedata_TtShortMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_phonedata_TtShortMessage_ShortMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_phonedata_TtShortMessage_ShortMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024TtShortMessage.proto\022\tphonedata\"\321\001\n\016Tt" +
      "ShortMessage\022\017\n\007request\030\001 \001(\010\022\020\n\010respons" +
      "e\030\002 \001(\010\022<\n\014shortMessage\030\003 \003(\0132&.phonedat" +
      "a.TtShortMessage.ShortMessage\032^\n\014ShortMe" +
      "ssage\022\023\n\013numberPhone\030\001 \001(\t\022\017\n\007message\030\002 " +
      "\001(\t\022\014\n\004time\030\003 \001(\t\022\014\n\004type\030\004 \001(\005\022\014\n\004name\030" +
      "\005 \001(\tB\'\n\017com.qzy.tt.dataB\024TtShortMessage" +
      "Protosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_phonedata_TtShortMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_phonedata_TtShortMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_phonedata_TtShortMessage_descriptor,
        new String[] { "Request", "Response", "ShortMessage", });
    internal_static_phonedata_TtShortMessage_ShortMessage_descriptor =
      internal_static_phonedata_TtShortMessage_descriptor.getNestedTypes().get(0);
    internal_static_phonedata_TtShortMessage_ShortMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_phonedata_TtShortMessage_ShortMessage_descriptor,
        new String[] { "NumberPhone", "Message", "Time", "Type", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
